### ISSUE TITLE
Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by pbhuvanesh** [hivedb/hive#429] opened 2020-09-10 12:32 UTC
I've been getting the below error quite frequently.

```
E/flutter (17333): #0      BinaryReaderImpl.readFrame 
package:hive/…/binary/binary_reader_impl.dart:249
E/flutter (17333): #1      FrameHelper.framesFromBytes 
package:hive/…/binary/frame_helper.dart:17
E/flutter (17333): #2      FrameIoHelper.framesFromFile 
package:hive/…/io/frame_io_helper.dart:41
E/flutter (17333): <asynchronous suspension>
E/flutter (17333): #3      StorageBackendVm.initialize 
package:hive/…/vm/storage_backend_vm.dart:82
E/flutter (17333): <asynchronous suspension>
E/flutter (17333): #4      BoxBaseImpl.initialize 
package:hive/…/box/box_base_impl.dart:90
E/flutter (17333): #5      HiveImpl._openBox 
package:hive/src/hive_impl.dart:106
E/flutter (17333): <asynchronous suspension>
E/flutter (17333): #6      HiveImpl.openBox 
package:hive/src/hive_impl.dart:135
E/flutter (17333): #7      main 
package:kaadhal_client/main.dart:17
E/flutter (17333): #8      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (17333): #9      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (17333): #10     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (17333): #11     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (17333): #12     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (17333): #13     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (17333): #14     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
E/flutter (17333): #15     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
E/flutter (17333): #16     HiveImpl.openBox (package:hive/src/hive_impl.dart)
E/flutter (17333): #17     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (17333): #18     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (17333): #19     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (17333): #20     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (17333): #21     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (17333): #22     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (17333): #23     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
E/flutter (17333): #24     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
E/flutter (17333): #25     HiveImpl._openBox (package:hive/src/hive_impl.dart)
E/flutter (17333): #26     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (17333): #27     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (17333): #28     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (17333): #29     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (17333): #30     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (17333): #31     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (17333): #32     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
E/flutter (17333): #33     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
E/flutter (17333): #34     StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart)
E/flutter (17333): #35     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (17333): #36     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (17333): #37     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (17333): #38     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (17333): #39     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (17333): #40     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (17333): #41     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
E/flutter (17333): #42     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
E/flutter (17333): #43     FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart)
E/flutter (17333): #44     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (17333): #45     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (17333): #46     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (17333): #47     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (17333): #48     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (17333): #49     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (17333): #50     Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)
E/flutter (17333): #51     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (17333): #52     _CustomZone.run  (dart:async/zone.dart:1093:19)
```

**Comment by LOLwierd** [comment] 2020-10-14 11:53
Same here. I changed nothing in my code, but this error popped from nowhere.

**Comment by TheMisir** [comment] 2020-10-15 06:48
Do you have reproducible example?

**Comment by TheMisir** [comment] 2020-10-15 06:48
Duplicate of #263

**Closed by TheMisir** 2020-10-15 06:48 UTC
