### ISSUE TITLE
Hive crash when using hydrated bloc

### ISSUE THREAD

**Issue by talmor-guy** [hivedb/hive#423] opened 2020-09-06 13:48 UTC
Some users of my app are experiencing a crash when the app starts. The log of the crash is as follows:

2020-08-19 13:26:48.192 32012-32084/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub. 
   #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249)  
   #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17)   
   #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41)    <asynchronous suspension>   
   #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82)    <asynchronous suspension>   
    #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:90)    <asynchronous suspension>   
    #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:111)    <asynchronous suspension>  
    #6      HydratedStorage.build.<anonymous closure> (package:hydrated_bloc/src/hydrated_storage.dart:62)    <asynchronous suspension>  
     #7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34)    <asynchronous suspension>    
     #8      main (package:lumen/main.dart:92)    <asynchronous suspension>

Android, hydrated_bloc 6.0

**Comment by TheMisir** [comment] 2020-09-06 15:06
Duplicate of #263

**Closed by TheMisir** 2020-09-06 15:06 UTC
Labels: problem
