### ISSUE TITLE
add functionality for saving unique data as extension

### ISSUE THREAD

**Issue by proismailshah** [hivedb/hive#830] opened 2021-11-13 17:39 UTC
**Steps to Reproduce**
I want to store data from server to my local,
I am using the "Box.add()" method but this method is repeating the values
I tried little bit my self but there was no benefit

**Code sample**
```
extension on Box<dynamic> {
  Set<dynamic> get toSet => Set<dynamic>.of(this);
}
```
I tried this code but it does not work because of Box<dynamic> type

Thanks in Advance

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [latest]
 - Hive version: [latest]

**Comment by keezysilencer** [comment] 2021-12-17 13:52
Duplicate of #842

**Closed** 2022-01-06 12:16 UTC
Labels: problem
