### ISSUE TITLE
Getting error "Because every version of flutter_test from sdk depends on path 1.7.0 and hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive_flutter >=0.3.0-dev." after addeing   hive_flutter: ^0.3.0+2

### ISSUE THREAD

**Issue by artmelkonyan** [hivedb/hive#313] opened 2020-05-15 14:07 UTC
**Steps to Reproduce**
Added in pubspec.yaml
dependencies:
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

and run 
```
flutter pub get
```
get error
```
Running "flutter pub get" in aebinfo...                         
Because every version of flutter_test from sdk depends on path 1.7.0 and hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive_flutter >=0.3.0-dev.
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
```
 Flutter (Channel master, 1.19.0-2.0.pre.71, on Microsoft Windows [Version 10.0.18363.778], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by Safort** [comment] 2020-05-16 08:29
I got the same error after updating flutter.

**Comment by NauzetAduen** [comment] 2020-05-16 18:26
me too, can't use pub get

**Comment by ToruNagao** [comment] 2020-05-17 00:21
same here.

**Comment by sgehrman** [comment] 2020-05-17 05:21
same here

**Comment by marcelgarus** [comment] 2020-05-17 10:10
Duplicate of #285.

**Temporary fix:** Add the following to your `pubspec.yaml`:
```dart
dependency_overrides:
  path: 1.7.0
```

**Comment by artmelkonyan** [comment] 2020-05-17 15:39
> Duplicate of #285.
> 
> **Temporary fix:** Add the following to your `pubspec.yaml`:
> 
> ```dart
> dependency_overrides:
>   path: 1.7.0
> ```

Ok thanks it solve my issue

**Closed** 2020-05-17 15:39 UTC
Labels: problem

**Comment by EagleSigma** [comment] 2020-06-06 18:18
Solved my too!  Thanks!

**Comment by YazeedAlKhalaf** [comment] 2020-07-12 15:21
Mine is not solved. Where to put this:
```dart
dependency_overrides:
  path: 1.7.0
```

**Comment by anandsubbu007** [comment] 2020-07-19 08:09
Hive installation is confusing & harder.
if I override path version then it shows version error in dartx, if I override its version then it shows version error in characters. 
still, version issue is not cleared. please update the version of packages used in hive

**Comment by kaiserleka** [comment] 2020-07-22 06:05
> Mine is not solved. Where to put this:
> 
> ```dart
> dependency_overrides:
>   path: 1.7.0
> ```

Below dependicies in pubspec.yaml file

```
dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  path: 1.7.0
```

**Comment by ashishbairwa** [comment] 2020-08-26 07:50
It's still a problem. Need a solid fix.

**Comment by TheMisir** [comment] 2020-08-26 07:52
> It's still a problem. Need a solid fix.

Could you write exact error message here? The issue was fixed after hive is updated a month ago.

**Comment by islamyoussef** [comment] 2020-10-03 16:22
I got the same ERROR and solved by the following steps

- I used older version it was [flutter_launcher_icons: "^0.7.0"]

- I wrote the following code in the same file [pubspec.yaml] but changed 2 values (android value and image path)
  flutter_icons:
    android: true   >>> it was "launcher_icon" but I changed it to true
    ios: true
    image_path: "my image path"

- In terminal I wrote the following codes
  flutter pub get then press ENTER
  flutter pub run flutter_launcher_icons:main   then press ENTER
  flutter run then press ENTER

These steps solved my issue, i hope it helps you too< GOOD LUCK

https://pub.dev/packages/flutter_launcher_icons/versions/0.7.0
![Capture](https://user-images.githubusercontent.com/25922224/94996479-517fba00-05a5-11eb-8b28-2c48d4103c9e.PNG)

**Comment by yoonjiyong** [comment] 2020-11-25 01:26
dependency_overrides:
  path: 1.7.0

I got this message
depends on dependency_overrides any which doesn't exist (could not find package dependency_overrides at https://pub.dartlang.org), version solving failed.

**Comment by AliEasy** [comment] 2020-12-30 13:29
using `path: ^1.7.0` instead of `path: 1.7.0` Worked for me

```
dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  path: ^1.7.0
```

**Comment by leedre** [comment] 2021-01-28 21:34
`flutter channel stable`
`flutter upgrade`
`flutter clean`

Worked for me. Good luck!

**Comment by pratikbutani** [comment] 2021-03-13 12:21
Have you checked [this article](https://pratikbutani.medium.com/flutter-2-upgrade-flutter-version-solving-failed-error-33ac1087cb6b)
