### ISSUE TITLE
Key order in Hive

### ISSUE THREAD

**Issue by andreademasi** [hivedb/hive#490] opened 2020-11-14 12:50 UTC
**Question**
Is there a way to specify a key order in hive like an ordered list? 

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.3
 - Hive version: ^1.4.4

**Comment by TheMisir** [comment] 2020-11-14 13:30
Duplicate of #462

**Closed by TheMisir** 2020-11-14 13:30 UTC
Labels: question

**Comment by andreademasi** [comment] 2020-11-14 13:57
@TheMisir thanks for the reply, is it possible to order the box based on its values?

**Comment by TheMisir** [comment] 2020-11-14 14:19
Not directly with Hive but you can apply sorting to `Hive.box('name').values`.

**Comment by andreademasi** [comment] 2020-11-14 14:37
So every time i put a new value in the box i have to sort the box?

**Comment by TheMisir** [comment] 2020-11-14 15:00
> So every time i put a new value in the box i have to sort the box?

You can also sort items before building UI. It's like sorting items in SQL using ORDER BY. You can write simple cache system to reduce processing time instead of sorting on every box sort only if something is changed. It might sound a bit complicated but actually it's same as querying SQL data with ORDER BY statement.
