### ISSUE TITLE
Type matching error on getting List from box

### ISSUE THREAD

**Issue by Tumist76** [hivedb/hive#327] opened 2020-06-03 04:54 UTC
I have a List<PaymentSession> which is being stored in the box with constant index. When I try to get it from the box, i get the following error: 

```dart
**_TypeError (type 'List<dynamic>' is not a subtype of type 'List<PaymentSession>')** 
```

As I see in the issue [Issue #33 ](https://github.com/hivedb/hive/issues/33), this should be fixed by now, but I still had to use cast.

It works this way:

```dart
static Future<List<PaymentSession>> getUnfinishedPaymentSessions() async {
    var sessionBox = await Hive.openBox(BoxNames.UserState);
    List<dynamic> sessionsRaw =
        await sessionBox.get(HiveKeys.UnfinishedPaymentSessions);
    List<PaymentSession> sessions = sessionsRaw.cast<PaymentSession>();
    return sessions;
}
```

But it thows error mentioned above if I do:

```dart
static Future<List<PaymentSession>> getUnfinishedPaymentSessions() async {
    var sessionBox = await Hive.openBox(BoxNames.UserState);
    List<PaymentSession> sessions =
        await sessionBox.get(HiveKeys.UnfinishedPaymentSessions);
    return sessions;
}
```

Package versions used:

```dart
hive: ^1.4.1+1
build_runner: ^1.0.0
hive_generator: ^0.7.0+2
```

**Comment by nateshmbhat** [comment] 2020-06-05 14:55
Same issue for me too.

**Comment by nateshmbhat** [comment] 2020-06-05 14:59
I'm Using the HEAD of master branch for both hive_flutter and hive_generator. 
And hive: ^1.4.1+1

**Comment by nateshmbhat** [comment] 2020-06-05 15:00
This is a blocker for me since the typecase happens inside the box_impl .

Issues occurs in : 

```
E get(dynamic key, {E defaultValue}) {
    checkOpen();

    var frame = keystore.get(key);
    if (frame != null) {
      return frame.value as E;
    } else {
      return defaultValue;
    }
  }
```


frame.value is casted to E.

**Comment by TheMisir** [comment] 2020-09-04 17:28
You have to cast list as you did in first example.

**Comment by TheMisir** [comment] 2020-09-04 17:31
Duplicate of #295

**Closed by TheMisir** 2020-09-04 17:31 UTC
Labels: problem
