### ISSUE TITLE
Hive Flutter ^0.3.0+2 depends upon path <1.7.0 fails pub get

### ISSUE THREAD

**Issue by vaishnavmhetre** [hivedb/hive#299] opened 2020-04-26 12:24 UTC
**Steps to Reproduce**

pub get following provided dependencies, 

**Code sample**

**_pub get_ Stacktrace**

```
Because every version of flutter_test from sdk depends on path 1.7.0 and hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive_flutter >=0.3.0-dev.

So, because expense depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because expense depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.)
```
[Gist to pubspec.yaml](https://gist.github.com/vaishnavmhetre/aa8cb16bcee063e9ab6a873826737c2e)

[Gist to pubspec.lock (mentions all installed versions of packages)](https://gist.github.com/vaishnavmhetre/5c82b8fccdb9694a03cd254f97aa4386)

**Version**
 - Platform: Linux (dev env)
 - Flutter version: (Channel master, v1.18.0-9.0.pre.12)
 - Hive version: ["1.4.1+1"]

**Comment by jibiel** [comment] 2020-04-26 12:55
Duplicate of https://github.com/hivedb/hive/issues/285.

**Comment by vaishnavmhetre** [comment] 2020-05-05 02:59
Pardon, I was on dev branch of flutter, possibly why issues arouse. Back to stable branch and everything is fine.

**Closed** 2020-05-05 02:59 UTC
Labels: problem
