### ISSUE TITLE
How to securely import existing data into the flutter hive database?

### ISSUE THREAD

**Issue by sinshev** [hivedb/hive#471] opened 2020-10-18 20:25 UTC
There are a lot of examples of how to create a box, write data into it, read the data, etc. This means the app does not need any initial data. 
How can I preload data on the app installation or initial launch?
Example:
I can add my_database.db to assets. Read it and create an encrypted hive box out of it.
The problem is adding my_database.db to assets is not secure.

So what is the best (and secure) way to import data into the flutter application?

**Comment by robinjohn** [comment] 2020-11-17 02:02
If your current data 'my_database.db' is already on Hive db, then you can be able to a manual migration from your existing no-encrypted Hive boxes to encrypted Hive boxes. 
(cc: @TheMisir @leisim )

Steps:
1. Check if my_database.db exists
2. If no, no migration, just proceed directly by opening new Boxes with encryption. and exit the below steps.
3. If yes, and if non-empty, open the current database and copy them to temporary variables or temporary Class objects.
4. Create an encryption key using Flutter Secure Storage or other means.
5. Open the new Boxes using the encryption key above, and for each Box data, go over each item (the key-value) from temporary variables/temporary class variables and `put` them to the new encrypted Box.

For reference, you may check https://github.com/hivedb/hive/issues/487 which does the same migration from unencrypted Hive db to encrypted Hive.

**Comment by TheMisir** [comment] 2020-11-17 06:27
Thanks @robinjohn 

Duplicate of #487

**Comment by TheMisir** [comment] 2020-11-17 06:27
Duplicate of #487

**Closed by TheMisir** 2020-11-17 06:27 UTC
Labels: question

**Comment by sinshev** [comment] 2020-11-23 21:32
@robinjohn The key problem is NOT migrating from unencrypted boxes to encrypted but securely adding the initial database to the application.
I have a .csv file with 300 000 rows of data which should be somehow imported into the application on the first app launch or installation.
I can simply add this .csv file as an asset and read from it, but using this approach is not secure. As far as I know, the assets can be easily extracted if you have root access to the device.

**Comment by robinjohn** [comment] 2020-11-23 23:18
Hi @sinshev , indeed the problem mentioned above is for migration. Let's say you have an app existing with customers data saved into hive db. Now I, as app developer, want to encrypt all the customer's data going forward. 
There are 2 cases here: 
#1: Those apps with no saved app data prior or new app installed: It's clear. Need to open the box as encrypted, encrypt the data using a secure key and save it into a secure storage ( eg: flutter_secure_storage). 
#2: Existing apps already installed on customer's phones: These data is already saved in the Hive db structure defined previously. For these data, need to manually take a back up, open the new hive db structure and copy into it. 

Your previous comment stated, applies for above case #1.
