### ISSUE TITLE
Inheritance - TypeAdapter for child class is broken

### ISSUE THREAD

**Issue by rubenvereecken** [hivedb/hive#478] opened 2020-10-29 10:07 UTC
**Steps to Reproduce**
Given this inheritance tree:
- `BaseUser` extends `HiveObject`, has some HiveField-annotated properties
- `User` extends `BaseUser`, has some more properties

When generating a TypeAdapter for `User`, its `read()` method is broken. It does not call the constructor with all of its arguments, that is, without the inherited properties. Strangely though, the `write()` method is fine and perfectly writes out all the inherited properties too.

**Code sample**

`base_user_model.dart`:
```dart 
class BaseUser extends LessgoBaseModel<String> with EquatableMixin {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String publicId;
  @HiveField(2)
  final String firstName;
  @HiveField(3)
  final String lastName;
  @HiveField(4)
  final bool studentVerified;
  @HiveField(5)
  final String gender;
  @HiveField(6)
  final String work;
  @HiveField(7)
  final String school;
  @HiveField(8)
  final String about;
  @HiveField(9)
  final List<String> interests;
  @HiveField(10)
  final List<ProfilePicture> pictures;

  // Reserving Hive fields 11-19 for expansion of BaseUser

  BaseUser({
    this.id,
    this.publicId,
    this.firstName,
    this.lastName,
    this.studentVerified,
    this.gender,
    this.work,
    this.school,
    this.about,
    this.interests,
    this.pictures,
  });
}
```

`user_model.dart`:
```dart
part 'user_model.g.dart';

@HiveType(typeId: LessgoHiveType.User)
class User extends BaseUser {
  @HiveField(30)
  final String email;
  @HiveField(31)
  final String referrer;
  @HiveField(32)
  final Location location;
  @HiveField(33)
  final DateTime dateOfBirth;
  @HiveField(34)
  final bool ageVerified;
  @HiveField(35)
  final UserSetting settings;
  @HiveField(36)
  final UserNotificationSetting notificationSettings;

  User({
    // Copied over from super
    id,
    publicId,
    firstName,
    lastName,
    studentVerified,
    gender,
    work,
    school,
    about,
    interests,
    pictures,
    this.email,
    this.referrer,
    this.location,
    this.dateOfBirth,
    this.ageVerified,
    this.settings,
    this.notificationSettings,
  }) : super(
          id: id,
          publicId: publicId,
          firstName: firstName,
          lastName: lastName,
          studentVerified: studentVerified,
          gender: gender,
          work: work,
          school: school,
          about: about,
          interests: interests,
          pictures: pictures,
        );
}
```

The generated Adapter looks as follows. Note how the read and write methods don't match in the fields that they use.
```dart

class UserAdapter extends TypeAdapter<User> {
  @override
  final int typeId = 2;

  @override
  User read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return User(
      email: fields[30] as String,
      referrer: fields[31] as String,
      location: fields[32] as Location,
      dateOfBirth: fields[33] as DateTime,
      ageVerified: fields[34] as bool,
      settings: fields[35] as UserSetting,
      notificationSettings: fields[36] as UserNotificationSetting,
    );
  }

  @override
  void write(BinaryWriter writer, User obj) {
    writer
      ..writeByte(18)
      ..writeByte(30)
      ..write(obj.email)
      ..writeByte(31)
      ..write(obj.referrer)
      ..writeByte(32)
      ..write(obj.location)
      ..writeByte(33)
      ..write(obj.dateOfBirth)
      ..writeByte(34)
      ..write(obj.ageVerified)
      ..writeByte(35)
      ..write(obj.settings)
      ..writeByte(36)
      ..write(obj.notificationSettings)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.publicId)
      ..writeByte(2)
      ..write(obj.firstName)
      ..writeByte(3)
      ..write(obj.lastName)
      ..writeByte(4)
      ..write(obj.studentVerified)
      ..writeByte(5)
      ..write(obj.gender)
      ..writeByte(6)
      ..write(obj.work)
      ..writeByte(7)
      ..write(obj.school)
      ..writeByte(8)
      ..write(obj.about)
      ..writeByte(9)
      ..write(obj.interests)
      ..writeByte(10)
      ..write(obj.pictures);
  }

// Cut some out for brevity
}
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.1
 - Hive version: 1.4.4+1
- hive_generator: 0.8.1

**Comment by rubenvereecken** [comment] 2020-10-29 10:12
I should add that I'm aware of #70 where @leisim explicitly states that it should be possible to just annotate the parent class' fields, which is the approach followed here.

**Comment by mohammadne** [comment] 2020-10-29 21:13
any update ?

**Comment by TheMisir** [comment] 2020-10-30 16:52
Duplicate of #442

**Closed by TheMisir** 2020-10-30 16:52 UTC
Labels: problem
