### ISSUE TITLE
Unhandled Exception: HiveError: This should not happen. (permanently)

### ISSUE THREAD

**Issue by Ahmadre** [hivedb/hive#512] opened 2020-12-12 01:58 UTC
**Error-Message**
```
Performing hot restart...
Syncing files to device macOS...
Restarted application in 606ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
#1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
#2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
<asynchronous suspension>
#3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:11)
<asynchronous suspension>
#4      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:9)
<asynchronous suspension>
#5      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:12)
<asynchronous suspension>
#6      AppNotifier.init (package:minesweeper/app/service.dart:55:11)
<asynchronous suspension>
#7      main (package:minesweeper/main.dart:11:19)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
#1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
#2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
<asynchronous suspension>
#3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:11)
<asynchronous suspension>
#4      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:9)
<asynchronous suspension>
#5      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:12)
<asynchronous suspension>
#6      AppNotifier.init (package:minesweeper/app/service.dart:55:11)
<asynchronous suspension>
#7      main (package:minesweeper/main.dart:11:19)
<asynchronous suspension>
```

**Steps to Reproduce**
Try once in a lifetime of your app to cancel a running Flutter app and boom you got the error.

**Code sample**
```
    if (!kIsWeb) Hive.init((await getApplicationDocumentsDirectory()).path);
    box = await Hive.openBox('my.box');
```

**Version**
 - Platform: iOS, Android, Mac, Web
 - Flutter version: 1.25.0-8.0.pre
 - Hive version: 1.4.4+1

**Comment by Ahmadre** [comment] 2020-12-12 03:55
Workaround: Rename your box, don't use special characters and you're safe!

**Comment by TheMisir** [comment] 2020-12-12 11:07
Duplicate of #263

**Closed by TheMisir** 2020-12-12 11:07 UTC
Labels: problem
