### ISSUE TITLE
Plans to become null safe?

### ISSUE THREAD

**Issue by HarvsG** [hivedb/hive#509] opened 2020-12-08 19:02 UTC
**Is your feature request related to a problem? Please describe.**
I am developing an app, I have decided to use flutter's null safe preview as I wish the app to be future-proofed for the upcoming change and I want experience coding in a null-safe language.

**Describe the solution you'd like**
It would be great to know hive's timeline for migrating to null-safe dart. Failing that it would be great to know if there are any top tips for managing hive's API. E.g "Always assume a hive method could return null"

**Comment by TheMisir** [comment] 2020-12-08 19:26
I'll work on null safety in a coming days or week. I'm a bit busy these days. Sorry for the delay :(

**Comment by HarvsG** [comment] 2020-12-08 20:20
:) Thanks, no hurry! Just great to know it's in the near-future!

**Comment by mbaumgartenbr** [comment] 2020-12-09 16:14
Hey @leisim could you get involved with the migration to NNBD? I think it would be a lot of work to @TheMisir do by himself. I would help but I don't have the knowledge required to the job. As Hive user I'm very hyped to see it migrated!

**Comment by leisim** [comment] 2020-12-09 21:27
@mbaumgartenbr This week I have a lot of work and a few deadlines but over christmas I'll have some time to implement NNBD. It should not be hard at all, just a lot of work  😅

**Comment by mbaumgartenbr** [comment] 2020-12-09 21:31
Great news! Take your time 😁
Btw, great work with isar, I'm looking forward to use it!

**Comment by leisim** [comment] 2020-12-09 21:35
@mbaumgartenbr Isar is so much work but I made good progress recently. In the next few days I hope to run the first query from Dart 😊

**Comment by mbaumgartenbr** [comment] 2020-12-09 21:36
Awesome! Take it easy!

**Comment by TheMisir** [comment] 2020-12-09 22:18
Duplicate of #496

**Closed by TheMisir** 2020-12-09 22:18 UTC
Labels: enhancement
