### ISSUE TITLE
HiveError: This should not happen. Please open an issue on GitHub.... HiveError binary_reader_impl.dart in BinaryReaderImpl.readFrame

### ISSUE THREAD

**Issue by priyabratap** [hivedb/hive#673] opened 2021-05-22 16:58 UTC
**Error**
HiveError binary_reader_impl.dart in BinaryReaderImpl.readFrame

**Stack trace**
```
binary_reader_impl.dart in BinaryReaderImpl.readFrame at line 249 within hive
frame_helper.dart in FrameHelper.framesFromBytes at line 17 within hive
frame_io_helper.dart in FrameIoHelper.framesFromFile at line 41 within hive
Called from: <asynchronous suspension>
storage_backend_vm.dart in StorageBackendVm.initialize at line 82 within hive
Called from: <asynchronous suspension>
hive_impl.dart in HiveImpl._openBox at line 106 within hive
Called from: <asynchronous suspension>
hive_impl.dart in HiveImpl.openBox at line 135 within hive
Called from: <asynchronous suspension>
controller.dart in NotificationController.markNotificationAsRead at line 138 within myproject
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 2.2
 - Hive version:   
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

**Comment by TheMisir** [comment] 2021-05-23 00:21
Duplicate of #263

**Closed by TheMisir** 2021-05-23 00:21 UTC
Labels: problem
