### ISSUE TITLE
Bad State No element when putting a Map into a Box

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [hivedb/hive#50] opened 2019-09-14 22:07 UTC
**Stacktrace**
```
Unhandled Exception: Bad state: No element
#0      ListQueue.removeFirst (dart:collection/queue.dart:729:25)
#1      Keystore.cancelTransaction (package:hive/src/box/keystore.dart:143:33)
#2      BoxImpl._writeFrame (package:hive/src/box/box_impl.dart:74:16)
<asynchronous suspension>
#3      BoxImpl.put (package:hive/src/box/box_impl.dart:57:12)
#4      Cache.setLastFetched (package:tavern/src/cache.dart:48:11)
#5      Cache.[]= (package:tavern/src/cache.dart:93:5)
#6      MapMixin.addAll (dart:collection/maps.dart:122:11)
#7      PageRepository.get (package:tavern/screens/home/home_bloc.dart:169:21)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)<…>
```

**Steps to Reproduce**
Not sure how. It only happens when the app starts, a box is opened and written to quickly. If I put a breakpoint and it pauses, then when it resumes, the error doesn't show up
**Code sample**
link to repo: https://github.com/ThinkDigitalSoftware/tavern
 Image of the frame, just in case you can grab something from it
<img width="847" alt="Screen Shot 2019-09-14 at 3 05 12 PM" src="https://user-images.githubusercontent.com/23037821/64914099-15ab5580-d701-11e9-88ff-36d5d2a4159f.png">

**Version**
 - Flutter 1.10.1 • channel dev • https://github.com/flutter/flutter.git
 - Framework • revision ce45c2d3e6 (8 days ago) • 2019-09-06 20:11:41 -0400
 - Engine • revision b9ce2500d9
 - Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 - Hive version: 1.0.0

**Comment by leisim** [comment] 2019-09-15 06:16
On which device does this error happen?

**Comment by leisim** [comment] 2019-09-15 07:12
What I believe happens: Hive can for some reason not write to the box file (not necessarily a bug in Hive). It then reverts the key transaction to be in sync with the disk. This operation fails (certainly a bug). I'll try to find the reason.

Thanks for reporting. If you find any more information or even a way to reproduce this, please share it here :+1:

**Comment by ThinkDigitalSoftware** [comment] 2019-09-16 15:55
Thanks. This is being tested on an iOS simulator. It was consistent in my code, which is available at the repo I linked to , however, I removed the class I was using it in because it wasn't necessary for the app. I can point you to the previous commit if you'd really like  to see it in action

**Comment by ThinkDigitalSoftware** [comment] 2019-09-16 15:55
Thanks. This is being tested on an iOS simulator. It was consistent in my code, which is available at the repo I linked to , however, I removed the class I was using it in because it wasn't necessary for the app. I can point you to the previous commit if you'd really like  to see it in action

**Comment by leisim** [comment] 2019-09-16 17:07
> I can point you to the previous commit if you'd really like to see it in action

That would be really helpful...

**Comment by ThinkDigitalSoftware** [comment] 2019-09-16 17:47
Here ya go. Commit 672e70d9

**Comment by leisim** [comment] 2019-09-16 18:45
Thanks for your help, I'll try to reproduce it...

**Comment by leisim** [comment] 2019-10-02 21:05
Sorry this was a bigger problem but it is now fixed with `1.1.0-beta`.

**Comment by ThinkDigitalSoftware** [comment] 2019-10-02 21:06
Thanks!

**Closed by leisim** 2019-10-02 21:05 UTC
Labels: bug

**Comment by ThinkDigitalSoftware** [comment] 2019-10-03 02:28
@leisim Do we need to clone the repo to get this fix?

**Comment by leisim** [comment] 2019-10-03 09:26
No you can use version `1.1.0-beta` from pub.dev

**Comment by marcelgarus** [comment] 2019-10-11 20:17
Is this really fixed? The following code throws this exact error with hive 1.0.0:
```dart
import 'package:hive/hive.dart';

void main(List<String> args) async {
  await Hive.init('.');
  var box = await Hive.openBox('number');
  box
    ..clear()
    ..putAll({
      1: 'a',
    });
}
```

Exception:
```
Unhandled exception:
Bad state: No element
#0      ListQueue.removeFirst (dart:collection/queue.dart:729:25)
#1      Keystore.cancelTransaction (package:hive/src/box/keystore.dart:143:33)
#2      BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:126:16)
<asynchronous suspension>
#3      BoxImpl.putAll (package:hive/src/box/box_impl.dart:97:12)
#4      main (package:test/main.dart:10:9)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     HiveImpl.openBox (package:hive/src/hive_impl.dart)
#13     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart)
#37     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by vamsireddytalla** [comment] 2022-11-07 06:56
when i try to write this code in flutter using hive with latest versions.

Product? product = _products.firstWhere((product) => product?.id == productId, orElse: () => null);
    if (product != null) {
      isExist = true;
    }

i am getting error like this

Unhandled Exception: type '() => Null' is not a subtype of type '(() => ApiLogs)?' of 'orElse'
