### ISSUE TITLE
Because hive_generator >=0.6.0 depends on dartx ^0.2.0 and chatting depends on dartx ^0.4.0, hive_generator >=0.6.0 is forbidden.

### ISSUE THREAD

**Issue by wann2** [hivedb/hive#310] opened 2020-05-11 08:10 UTC
**Question**
Because hive_generator >=0.6.0 depends on dartx ^0.2.0 and chatting depends on dartx ^0.4.0, hive_generator >=0.6.0 is forbidden.

So, because chatting depends on hive_generator ^0.7.0+2, version solving failed.
pub get failed (1; So, because chatting depends on hive_generator ^0.7.0+2, version solving failed.)

When I execute “pub get”, I got the above error.
The below is pubspec.yaml.
Could you help me how to fix it?

**Code sample**
environment:
sdk: “>=2.1.0 <3.0.0"

dependencies:
flutter:
sdk: flutter

agora_rtc_engine: ^1.0.11
animator: ^1.0.0+5 # old ok
cached_network_image: ^2.2.0+1
cloud_firestore: ^0.13.5
country_codes: ^0.1.0
cupertino_icons: ^0.1.3
dartx: ^0.4.0
#devicelocale: ^0.2.3
dio: ^3.0.9
firebase_analytics: ^5.0.11
firebase_auth: # use the latest version
firebase_core: ^0.4.4+3
firebase_messaging: ^6.0.13
firebase_storage: ^3.1.5
flt_telephony_info: ^0.1.3
flutter_facebook_login: ^3.0.0
flutter_image_compress: ^0.6.7
flutter_local_notifications: ^1.4.3
flutter_native_timezone: ^1.0.4
flutter_slidable: "^0.5.4"
geolocator: ^5.3.1
google_sign_in: ^4.4.4
hive: ^1.4.1+1
hive_flutter: ^0.3.0+2
http: ^0.12.1
intl: ^0.16.1
fluttertoast: ^4.0.1
image_cropper: ^1.2.1
image_picker: ^0.6.6+1
#moor: ^3.0.2
#moor_ffi: ^0.5.0
package_info: ^0.4.0+17
path_provider: ^1.6.7 # For OS-specific directory paths
path:
permission_handler: ^4.4.0+hotfix.4 # old ok
photo_view: ^0.9.2
provider: ^4.1.0
quiver: ^2.1.3
shared_preferences: ^0.5.7+1
sqflite: ^1.3.0+1
timezone: ^0.5.7
uuid: ^2.0.4

dev_dependencies:
flutter_test:
sdk: flutter

#moor_generator: # use the latest version
hive_generator: ^0.7.0+2
build_runner:

**Comment by marcelgarus** [comment] 2020-05-11 11:33
Duplicate of https://github.com/hivedb/hive/issues/247 (issue thread also contains a temporary fix)

**Comment by Nash0x7E2** [comment] 2020-05-13 00:09
#309 Fixes this

**Comment by dinit-bwd** [comment] 2020-05-14 10:56
package upgrade will solve the issue. Can you guys do it fase?

**Comment by mHaisham** [comment] 2020-05-14 23:52
Getting the issue. can we expect a fix soon.

**Comment by Nash0x7E2** [comment] 2020-05-15 18:26
As a workaround, I am using a dependency override to manually set the package.

**Comment by dinit-bwd** [comment] 2020-05-18 03:54
We cant go for production with dependency override. For developing i did the same. If you guys fix this, it will be very helpful

**Comment by marcelgarus** [comment] 2020-05-19 12:02
@dinit-bwd I know this is still just a temporary solution, but you can always [depend on one of the forks using git](https://dart.dev/tools/pub/dependencies#git-packages), which is safe as far as package-resolution goes.

**Comment by TheMisir** [comment] 2020-07-26 13:43
Fixed in latest version of hive_generator.

**Closed by TheMisir** 2020-07-26 13:43 UTC
Labels: question
