### ISSUE TITLE
Update dartx dependency to 0.4.0

### ISSUE THREAD

**Issue by shinayser** [hivedb/hive#308] opened 2020-05-05 20:24 UTC
I am receiving this errors when trying to build:

```
Because no versions of hive_generator match >0.7.0+2 <0.8.0 and hive_generator 0.7.0+2 depends on dartx ^0.3.0, hive_generator ^0.7.0+2 requires dartx ^0.3.0.
So, because mydenox_flutter depends on both dartx ^0.4.0 and hive_generator ^0.7.0+2, version solving failed.
pub get failed (1; So, because mydenox_flutter depends on both dartx ^0.4.0 and hive_generator ^0.7.0+2, version solving failed.)
```

**Comment by marcelgarus** [comment] 2020-05-06 10:26
Duplicate of #247

**Comment by kdmatrosov** [comment] 2020-05-07 06:29
When will this issue be fixed? With new stable Flutter hive_generator is totally broken

**Comment by AuX-x** [comment] 2020-05-07 09:04
I have this problem too. hope for fix

**Comment by marcelgarus** [comment] 2020-05-07 09:11
As pointed out in #247, you can override the dependency like this in your `pubspec.yaml`:
```dart
dependencies:
  ...

dependency_overrides:
  dartx: ^0.4.0
```

**Comment by Auuufff** [comment] 2020-05-07 09:18
@marcelgarus, this is not a good solution. This is a temporary fix to continue working, thanks for that.

**Comment by marcelgarus** [comment] 2020-05-07 09:34
Oh of course. This is temporary, sorry for not making that clear up front

**Comment by TheMisir** [comment] 2020-07-26 13:43
Fixed in latest version of the package

**Closed** 2020-07-26 13:43 UTC
Labels: enhancement
