### ISSUE TITLE
generated Type Adapter doesn't include all the parameters for the constructor !

### ISSUE THREAD

**Issue by nateshmbhat** [hivedb/hive#469] opened 2020-10-13 12:18 UTC
**Steps to Reproduce**
```
@HiveType(typeId: 2)
class RecentSearch {
  @HiveField(0)
  final String moduleName;

  @HiveField(1)
  final String moduleData;

  @HiveField(2)
  final int timestamp;

  @HiveField(3)
  final String key;

  ///Used to display the item in a recent search widget. The below data will be shown for the user.
  ///Defaults to moduleData
  @HiveField(4)
  final String displayData;

  RecentSearch({
    @required this.moduleName,
    @required this.moduleData,
    String displayData,
    String key,
    int timestamp,
  })  : timestamp = timestamp ?? DateTime.now().millisecondsSinceEpoch,
        displayData = displayData,
        key = key ?? '$moduleName-$moduleData';
}
```

The generated Typed Adapter class doesn't pass all the fields in the generated code for read method : 

```
  @override
  RecentSearch read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return RecentSearch(
      moduleName: fields[0] as String,
      moduleData: fields[1] as String,
    );
  }
```

Because of this, whenever a recent search object is saved in hive, though it is saved properly. when reading, all the rest of the fields will be "null".

Also : 
If i specify "@required" annotation for a parameter, that's not included in the constructor code : 
```
RecentSearch({
    @required this.moduleName,
    @required String myData,
    String displayData,
    String key,
    int timestamp,
  })  : moduleData = myData,
        timestamp = timestamp ?? DateTime.now().millisecondsSinceEpoch,
        displayData = displayData,
        key = key ?? '$moduleName-$moduleData';
}
```

This generates the below code, since myData parameter is not generated, it results in warning and error depending on analysis_options.yaml : 
```
return RecentSearch(
      moduleName: fields[0] as String,
    ); 

```

**Comment by mohammadne** [comment] 2020-10-29 21:36
any update ?

**Comment by TheMisir** [comment] 2020-10-30 16:50
Hive generator only fills property arguments that's annotated with `@HiveField` annotation.

**Comment by TheMisir** [comment] 2020-11-02 10:07
Duplicate of #442

**Closed by TheMisir** 2020-11-02 10:07 UTC
Labels: problem
