### ISSUE TITLE
Hive Generator null safety support

### ISSUE THREAD

**Issue by CodeDoctorDE** [hivedb/hive#566] opened 2021-02-19 20:16 UTC
**Question**
I followed the tutorial explained in https://dart.dev/null-safety/migration-guide .
I ran this command: `flutter pub outdated --mode=null-safety`
![image](https://user-images.githubusercontent.com/20452814/108556743-cacf3d80-72f7-11eb-9dd3-720b700bbabf.png)

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.27.0-4.0.pre]
 - Hive version: [e.g. 1.6.0-nullsafety.2]

**Comment by bernaferrari** [comment] 2021-03-03 20:23
It is because Hive is not null safe yet :(

**Comment by CodeDoctorDE** [comment] 2021-03-26 17:36
Then I change the question. Is there an option to add null safety support?

**Comment by TheMisir** [comment] 2021-03-26 17:40
> It is because Hive is not null safe yet :(

No it is, Hive >2.0.0 does supports null-safety.

**Comment by TheMisir** [comment] 2021-03-26 17:40
Duplicate of #584

**Comment by CodeDoctorDE** [comment] 2021-03-26 17:41
okay, my issue was older but okay :)

**Closed by TheMisir** 2021-03-26 17:40 UTC
Labels: question

**Comment by TheMisir** [comment] 2021-03-26 18:34
> okay, my issue was older but okay :)

Sorry for that, I had not noticed.

**Comment by bernaferrari** [comment] 2021-03-26 19:03
> No it is, Hive >2.0.0 does supports null-safety.

It supports now, but when the issue was created it didn't.
