### ISSUE TITLE
Make Hive working with @immutable class

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#225] opened 2020-02-14 13:33 UTC
@leisim  Hi there! 
It will be awesome to get this awesome plugin [Freezed](https://pub.dev/packages/freezed) working with immutable models, so we can have  immutable model that can be generated and stored directly in Hive database.

cc: @rrousselGit

**Comment by leisim** [comment] 2020-02-14 13:34
Thanks, I'll take a look. It will be hard to achieve this with the changes planned for Hive 2.0 but I'll try to figure it out.

**Comment by frank06** [comment] 2020-02-17 18:59
That would be great! I remember some time ago trying to tag my models as `@immutable` but got warnings as `HiveObject`s are mutable

**Comment by peekpt** [comment] 2020-02-17 21:21
@frank06 exactly that!

**Comment by rrousselGit** [comment] 2020-02-17 21:30
I suppose that instead of "working with Freezed", it's more of a "working with immutable models".

Freezed doesn't do anything fancy.

**Comment by marcelgarus** [comment] 2020-04-05 19:58
I'd also really love this to work. I'll try to find some time to look into the issues that occur when using <kbd>hive</kbd> with <kbd>freezed</kbd>. It would make our data classes so much shorter!

<details>
<summary>Hand-written immutable Hive data classes</summary>

```dart

@HiveType(typeId: TypeId.user)
class User implements Entity<User> {
  const User({
    @required this.id,
    @required this.firstName,
    @required this.lastName,
    @required this.email,
    @required this.schoolId,
    String displayName,
    @required this.avatarInitials,
    @required this.avatarBackgroundColor,
    @required this.permissions,
    @required this.roleIds,
  })  : assert(id != null),
        assert(firstName != null),
        assert(lastName != null),
        assert(email != null),
        assert(schoolId != null),
        displayName = displayName ?? '$firstName $lastName',
        assert(avatarInitials != null),
        assert(avatarBackgroundColor != null),
        assert(permissions != null),
        assert(roleIds != null);

  User.fromJson(Map<String, dynamic> data)
      : this(
          id: Id<User>(data['_id']),
          firstName: data['firstName'],
          lastName: data['lastName'],
          email: data['email'],
          schoolId: data['schoolId'],
          displayName: data['displayName'],
          avatarInitials: data['avatarInitials'],
          avatarBackgroundColor:
              (data['avatarBackgroundColor'] as String).hexToColor,
          permissions: (data['permissions'] as List<dynamic>).cast<String>(),
          roleIds: parseIds(data['roles']),
        );

  static Future<User> fetch(Id<User> id) async =>
      User.fromJson(await services.api.get('users/$id').json);

  @override
  @HiveField(0)
  final Id<User> id;

  @HiveField(1)
  final String firstName;

  @HiveField(2)
  final String lastName;

  String get shortName => '${firstName.chars.first}. $lastName';

  @HiveField(3)
  final String email;

  @HiveField(4)
  final String schoolId;

  @HiveField(5)
  final String displayName;

  @HiveField(7)
  final String avatarInitials;
  @HiveField(8)
  final Color avatarBackgroundColor;

  @HiveField(6)
  final List<String> permissions;
  bool hasPermission(String permission) => permissions.contains(permission);

  @HiveField(9)
  final List<Id<Role>> roleIds;
  bool get isTeacher => hasRole(Role.teacherName);
  bool hasRole(String name) {
    // TODO(marcelgarus): Remove the hard-coded mapping and use runtime lookup when upgrading flutter_cached and flattening is supported.
    final id = {
      Role.teacherName: '0000d186816abba584714c98',
    }[name];
    return id != null && roleIds.contains(Id<Role>(id));
  }

  @override
  bool operator ==(Object other) =>
      other is User &&
      id == other.id &&
      firstName == other.firstName &&
      lastName == other.lastName &&
      email == other.email &&
      schoolId == other.schoolId &&
      displayName == other.displayName &&
      avatarInitials == other.avatarInitials &&
      avatarBackgroundColor == other.avatarBackgroundColor &&
      permissions.deeplyEquals(other.permissions, unordered: true) &&
      roleIds.deeplyEquals(other.roleIds, unordered: true);
  @override
  int get hashCode => hashList([
        id,
        firstName,
        lastName,
        email,
        schoolId,
        displayName,
        avatarInitials,
        avatarBackgroundColor,
        permissions,
        roleIds
      ]);
}
```
</details>

<details>
<summary>Using freezed with Hive (doesn't work yet)</summary>

```dart
@freezed
@HiveType(typeId: TypeId.user)
abstract class User implements Entity<User>, _$User {
  const User._();
  const factory User({
    @HiveField(0) @required Id<User> id,
    @HiveField(1) @required String firstName,
    @HiveField(2) @required String lastName,
    @HiveField(3) @required String email,
    @HiveField(4) @required String schoolId,
    @HiveField(5) String displayName,
    @HiveField(7) @required String avatarInitials,
    @HiveField(8) @required Color avatarBackgroundColor,
    @HiveField(6) @required List<String> permissions,
    @HiveField(9) @required List<Id<Role>> roleIds,
  }) = _User;
  // displayName = displayName ?? '$firstName $lastName',

  static User fromJson(Map<String, dynamic> data) => User(
        id: Id<User>(data['_id']),
        firstName: data['firstName'],
        lastName: data['lastName'],
        email: data['email'],
        schoolId: data['schoolId'],
        displayName: data['displayName'],
        avatarInitials: data['avatarInitials'],
        avatarBackgroundColor:
            (data['avatarBackgroundColor'] as String).hexToColor,
        permissions: (data['permissions'] as List<dynamic>).cast<String>(),
        roleIds: parseIds(data['roles']),
      );

  static Future<User> fetch(Id<User> id) async =>
      User.fromJson(await services.api.get('users/$id').json);

  String get shortName => '${firstName.chars.first}. $lastName';

  bool hasPermission(String permission) => permissions.contains(permission);

  bool get isTeacher => hasRole(Role.teacherName);
  bool hasRole(String name) {
    // TODO(marcelgarus): Remove the hard-coded mapping and use runtime lookup when upgrading flutter_cached and flattening is supported.
    final id = {
      Role.teacherName: '0000d186816abba584714c98',
    }[name];
    return id != null; // && roleIds.contains(Id<Role>(id));
  }
}
```
</details>

**Comment by rubgithub** [comment] 2020-07-21 15:12
> I'd also really love this to work. I'll try to find some time to look into the issues that occur when using hive with freezed. It would make our data classes so much shorter!
> 
> EDIT: I just started looking into it, but because the [hive_generator](https://github.com/hivedb/hive_generator) repo got archived, I decided it's not worth the effort.
> 
> Hand-written immutable Hive data classes
> Using freezed with Hive (doesn't work yet)

Any update about this feature?

**Comment by marcelgarus** [comment] 2020-07-24 08:35
Sure. I have a kind of love-hate relationship with the Hive serializer. I think it got a lot of things right, but I also strongly disagree with some of the design decisions (like the format not being self-descriptive, like JSON, or the adapters having the responsibility to define their own ids, causing IDs to be scattered all over your project instead of being defined in one central place). I also wanted to use the serializer on its own separate from Hive, so in #152 I did some brainstorming with @leisim about how the serializer could be improved – and several great ideas came up. I wanted to play around with some of them, so I started writing a serializer with a slightly different approach, which ended up in [tape](https://pub.dev/package/tape). I also focused on great tooling, but it's not production-ready by a long shot. For the Hive replacement – [isar](https://github.com/isar/isar) – @leisim wrote a completely new serializer with some different design philosophies which also looks promising.

Tape does work with freezed, and I think the part of being able to use freezed could also be applied to Hive – I'm currently quite busy with studying and work stuff as well as other projects, so it's probably gonna take some time before I find time to look at it though. If anyone has spare time and feels like it, don't hesitate to code something up and file a PR. Tape already works with freezed, so in [the repo](https://github.com/marcelgarus/tape) you should find some guidance on how that could work. I'm also available for concrete questions, if you have any.

**Comment by marcelgarus** [comment] 2020-07-24 08:36
Sure. I have a kind of love-hate relationship with the Hive serializer. I think it got a lot of things right, but I also strongly disagree with some of the design decisions (like the format not being self-descriptive, like JSON, or the adapters having the responsibility to define their own ids, causing IDs to be scattered all over your project instead of being defined in one central place). I also wanted to use the serializer on its own separate from Hive, so in #152 I did some brainstorming with @leisim about how the serializer could be improved – and several great ideas came up. I wanted to play around with some of them, so I started writing a serializer with a slightly different approach, which ended up in [tape](https://pub.dev/package/tape). I also focused on great tooling, but it's not production-ready by a long shot. For the Hive replacement – [isar](https://github.com/isar/isar) – @leisim wrote a completely new serializer with some different design philosophies which also looks promising.

Tape does work with freezed, and I think the part of being able to use freezed could also be applied to Hive – I'm currently quite busy with studying and work stuff as well as other projects, so it's probably gonna take some time before I find time to look at it though. If anyone has spare time and feels like it, don't hesitate to code something up and file a PR. Tape already works with freezed, so in [the repo](https://github.com/marcelgarus/tape) you should find some guidance on how that could work. I'm also available for concrete questions, if you have any.

**Comment by zs-dima** [comment] 2020-09-21 14:46
Any updates?

**Comment by TheMisir** [comment] 2020-09-21 14:57
What do you mean by "working with @immutable class"? I haven't used `freezed` package, so I don't know what's exact issue.

**Comment by zs-dima** [comment] 2020-09-21 15:16
"@immutable class" is not about `freezed` only - you could read thread history for more details

**Comment by TheMisir** [comment] 2020-09-21 17:04
> "@immutable class" is not about `freezed` - you could read thread history for more details
> `freezed` just example
> it is just `Hive` blocker issue that force many users to use `Sembast` instead

I have tried adding `@immutable` to my hive models. But did not get any warnings or errors.

Does the issue is related to model adapters generated by hive_generator or caused when extending models with `HiveObject`?

**Comment by zs-dima** [comment] 2020-09-21 18:21
`@immutable` to my hive models
"@immutable classes" usually constructed using `with` or `implements`
so it will compile and run but it will store empty objects in the Hive DB.

I like Hive so hope it will be fixed once.

for example with `freezed` immutable class looks like:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'immutable_class.freezed.dart';
part 'immutable_class.g.dart';

@freezed
@HiveType(typeId: 5)
abstract class ImmutableClass with _$ImmutableClass {
  const factory ImmutableClass({
    @JsonKey(name: 'id', required: true, disallowNullValue: true) @HiveField(0) int id,
    @HiveField(1) int someField1,
    @HiveField(2) String someField2,
  }) = _ImmutableClass;

  factory ImmutableClass.fromJson(Map<String, dynamic> json) => _$ImmutableClassFromJson(json);
}
```

**Comment by TheMisir** [comment] 2020-09-21 19:41
I'm not planning to implement this feature. The implementation will be package specific (`freezed` in your example). Instead you can write your own hive adapter. Or at least human readable model classes (which hive generator currently supports). Fyi: hive_generator generates code for **fields** annotated with `HiveField` inside classes mentioned with `HiveType`. It doesn't checks for constructors or something else.

**Comment by zs-dima** [comment] 2020-09-21 19:47
Dart have no `@immutable classes` other then `packages specific` `built_value` `freezed` and etc (you could use @immutable only but is will not safe from setting fields)
So user have to choose reliable code with `specific packages` or non-reliable code with `Hive` - therefore many forced to use `Sembast`

**Comment by zs-dima** [comment] 2020-09-21 19:51
moreover
> hive_generator generates code for **fields** annotated with `HiveField` inside classes mentioned with `HiveType`.
* by the way, `freezed` generate **fields** annotated with `HiveField` inside classes mentioned with `HiveType` (as base class or mixin)
- and `Hive` still do not save objects correctly

**Comment by zs-dima** [comment] 2020-09-21 20:47
the only way I found to workarround it some-how, but it looks quite ugly with adapter name string, hope Hive will be improved to fix it:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'immutable_class.freezed.dart';
part 'immutable_class.g.dart';

@freezed
abstract class ImmutableClass with _$ImmutableClass {
  @HiveType(typeId: 5, adapterName: 'ImmutableClassAdapter')
  const factory ImmutableClass({
    @JsonKey(name: 'id', required: true, disallowNullValue: true) @HiveField(0) int id,
    @HiveField(1) int someField1,
    @HiveField(2) String someField2,
  }) = _ImmutableClass;

  factory ImmutableClass.fromJson(Map<String, dynamic> json) => _$ImmutableClassFromJson(json);
}
```

**Comment by TheMisir** [comment] 2020-09-21 21:17
What do you think about that @leisim ?

**Comment by RaviKavaiya** [comment] 2020-09-22 03:19
> the only way I found to workarround it some-how, but it looks quite ugly with adapter name string, hope Hive will be improved to fix it:
> 
> ```dart
> import 'package:freezed_annotation/freezed_annotation.dart';
> import 'package:hive/hive.dart';
> 
> part 'immutable_class.freezed.dart';
> part 'immutable_class.g.dart';
> 
> @freezed
> abstract class ImmutableClass with _$ImmutableClass {
>   @HiveType(typeId: 5, adapterName: 'ImmutableClassAdapter')
>   const factory ImmutableClass({
>     @JsonKey(name: 'id', required: true, disallowNullValue: true) @HiveField(0) int id,
>     @HiveField(1) int someField1,
>     @HiveField(2) String someField2,
>   }) = _ImmutableClass;
> 
>   factory ImmutableClass.fromJson(Map<String, dynamic> json) => _$ImmutableClassFromJson(json);
> }
> ```

@TheMisir I have been using this solution since last 3-4 months. And I didn't get any issues.
The problem with using Hive with Freezed is, Freezed creates Private classes (_$*), so for example, our class `Product` will have adapter called `_$ProductAdapter`, which we won't be able to access anywhere.

The solution is to manually provide `adapterName` just as this solution and it would work PERFECTLY.

So, to conclude, neither of the libraries are at fault.

**Comment by zs-dima** [comment] 2020-09-22 04:41
It's ugly to use String as name
What about trim start '_' and '$' symbols from adapter name by default? As adapter should not be private

**Comment by TheMisir** [comment] 2020-09-22 05:04
So the problem is adapter names. I can trim _$ part from adapter names.

**Comment by zs-dima** [comment] 2020-09-22 05:12
> I can trim _$ part from adapter names.
It could be awesome, thanks a lot

**Closed** 2020-09-23 16:46 UTC
Labels: enhancement

**Comment by TheMisir** [comment] 2020-09-23 16:51
Published to pub.dev. You will need to set min version to 0.7.2:

```yaml
dev_dependencies:
  hive_generator: ^0.7.2
```

**Comment by zs-dima** [comment] 2020-09-23 17:42
@TheMisir

`Adapter` still have '_' sign:
```dart
class _SomeClassAdapter extends TypeAdapter<_$_SomeClass> {
```

Thanks for the fast update, hope you will fix it as adapter name started with '_' sign could not be really used

Thanks in advance

**Comment by TheMisir** [comment] 2020-09-23 19:33
> @TheMisir
> 
> `Adapter` still have '_' sign:
> 
> ```dart
> class _SomeClassAdapter extends TypeAdapter<_$_SomeClass> {
> ```
> 
> Thanks for the fast update, hope you will fix it as adapter name started with '_' sign could not be really used
> 
> Thanks in advance

Oops 😅 Now fixing.

**Comment by TheMisir** [comment] 2020-09-23 19:56
Fixed and published!

**Comment by zs-dima** [comment] 2020-09-23 20:02
Wow, `Adapters` are generated correctly, awesome, thanks a lot for the fast fix!

**Comment by Mravuri96** [comment] 2020-09-25 15:20
any update to the docs, regarding these changes?

**Comment by mohammadne** [comment] 2020-10-20 11:21
is it possible to have sth like this for union classes ?

**HIVE**
```
@HiveType(typeId: 2)
enum AudioOrderDao {
  @HiveField(0)
  order,

  @HiveField(1)
  repeatOne,

  @HiveField(2)
  repeatAll,

  @HiveField(3)
  shuffle
}
```

**FREEZED**
```
@freezed
abstract class AudioOrder with _$AudioOrder {
  const factory AudioOrder.order() = _Order;
  const factory AudioOrder.repeatAll() = _RepeatAll;
  const factory AudioOrder.repeatOne() = _RepeatOne;
  const factory AudioOrder.shuffle() = _Shuffle;
}
```

thanks

**Comment by TheMisir** [comment] 2020-10-20 11:33
> is it possible to have sth like this for union classes ?
> 
> **HIVE**
> 
> ```dart
> @HiveType(typeId: 2)
> enum AudioOrderDao {
>   @HiveField(0)
>   order,
> 
>   @HiveField(2)
>   repeatAll,
> 
>   @HiveField(1)
>   repeatOne,
> 
>   @HiveField(3)
>   shuffle
> }
> ```
> 
> **FREEZED**
> 
> ```dart
> @freezed
> abstract class AudioOrder with _$AudioOrder {
>   const factory AudioOrder.order() = _Order;
>   const factory AudioOrder.repeatAll() = _RepeatAll;
>   const factory AudioOrder.repeatOne() = _RepeatOne;
>   const factory AudioOrder.shuffle() = _Shuffle;
> }
> ```
> 
> thanks

The first is enum and second one is class. They are not same thing. Anyways you could create custom type adapter for that.

**Comment by min-wai** [comment] 2020-12-15 08:43
> > is it possible to have sth like this for union classes ?
> > **HIVE**
> > ```dart
> > @HiveType(typeId: 2)
> > enum AudioOrderDao {
> >   @HiveField(0)
> >   order,
> > 
> >   @HiveField(2)
> >   repeatAll,
> > 
> >   @HiveField(1)
> >   repeatOne,
> > 
> >   @HiveField(3)
> >   shuffle
> > }
> > ```
> > 
> > 
> > **FREEZED**
> > ```dart
> > @freezed
> > abstract class AudioOrder with _$AudioOrder {
> >   const factory AudioOrder.order() = _Order;
> >   const factory AudioOrder.repeatAll() = _RepeatAll;
> >   const factory AudioOrder.repeatOne() = _RepeatOne;
> >   const factory AudioOrder.shuffle() = _Shuffle;
> > }
> > ```
> > 
> > 
> > thanks
> 
> The first is enum and second one is class. They are not same thing. Anyways you can create custom type adapter for that.

How do I write a custom adapter for a class with several factory constructors and varying parameters?

```dart
@freezed
abstract class AudioOrder with _$AudioOrder {
  const factory AudioOrder.order(String id, String message, String type) = Order;
  const factory AudioOrder.repeatAll(String message, String type) = RepeatAll;
  const factory AudioOrder.repeatOne(String id, String type) = RepeatOne;
  const factory AudioOrder.shuffle(String type) = Shuffle;
}
```

**Comment by casvanluijtelaar** [comment] 2021-09-20 12:03
sorry to hijack, when running hive_generator on this class it's not generating the type adapter

``` dart
import 'package:flutter/painting.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'wled_device.freezed.dart';
part 'wled_device.g.dart';

@HiveType(typeId: 2)
enum DeviceStatus {
  @HiveField(0)
  functional,
  @HiveField(1)
  unreachable,
  @HiveField(2)
  error,
}

@freezed
class WledDevice with _$WledDevice {
  @HiveType(typeId: 1)
  const factory WledDevice({
    // device IP (can also be hostname if applicable)
    @HiveField(0) required String address,
    // device display name ("Server Description")
    @HiveField(1) required String name,
    // Current connection status
    @HiveField(2) @Default(DeviceStatus.functional) DeviceStatus status,
    // If the light name is custom, the name returned
    // by the API response will be ignored
    @HiveField(3) @Default(false) bool nameIsCustom,
    // if the wled device is saved to the local device
    @HiveField(4) @Default(false) bool isSaved,
    // Disabled devices don't get polled or show up in the list
    @HiveField(5) @Default(true) bool isEnabled,
    // There are two vars for brightness to discern
    // API responses from slider updates
    @HiveField(6) @Default(0.9) double brightness,
    // the currently active device color
    @HiveField(7) @Default(Color.fromRGBO(255, 255, 255, 0.2)) Color color,
  }) = _WledDevice;
}
```

it did generate the `DeviceStatus` adapter correctly, and I have both that adapter and a color adapter registered
``` dart
  await Hive.initFlutter();
  Hive.registerAdapter(DeviceStatusAdapter());
  Hive.registerAdapter(ColorAdapter());
  //Hive.registerAdapter(WledDeviceAdapter());
```
am I missing something super obvious?

<details>
  <summary markdown="span">pubspec.yaml & build_runner output</summary>

``` yaml
name: wled
description: A cross-platform application for interacting with WLED devices

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  bloc: ^7.2.0-dev.3
  bloc_concurrency: ^0.1.0-dev.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  multicast_dns: ^0.3.1
  rive: ^0.7.28
  rxdart: ^0.27.2
  sleek_circular_slider: ^2.0.1
  webview_flutter: ^2.0.14
  xml: ^5.1.0

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.2
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.3
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.1
  json_serializable: ^5.0.1
  very_good_analysis: ^2.3.0

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-Regular.ttf
          weight: 400

# internationalization settings
flutter_intl:
  enabled: true
  class_name: Localization
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

# set flutter splash screen
flutter_native_splash:
  color: "#1D1D1D"
  image: assets/images/splash.png
  fullscreen: true
  android12: false

# set flutter app icon
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/fallback.png"
  image_path_android: "assets/images/fallback.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"

# set flutter app name
flutter_app_name:
  name: "WLED"
```


``` powershell
flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 731ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 159ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.3s

[INFO] Running build...
[INFO] 1.1s elapsed, 0/8 actions completed.
[INFO] 2.3s elapsed, 0/8 actions completed.
[INFO] 3.3s elapsed, 0/8 actions completed.
[INFO] 4.6s elapsed, 0/8 actions completed.
[INFO] 5.7s elapsed, 0/8 actions completed.
[INFO] 8.9s elapsed, 1/8 actions completed.
[INFO] 18.3s elapsed, 1/8 actions completed.
[INFO] 19.3s elapsed, 7/8 actions completed.
[INFO] 20.5s elapsed, 16/24 actions completed.
[INFO] 21.6s elapsed, 22/24 actions completed.
[INFO] 22.7s elapsed, 26/33 actions completed.
[WARNING] auto_route_generator:autoRouteGenerator on lib/core/app/app_router.dart:

WARNING => Because [DeviceControlView] has required parameters (deviceName) that can not be parsed from path,
@PathParam() and @QueryParam() annotations will be ignored.

[INFO] 24.0s elapsed, 33/49 actions completed.
[INFO] 25.1s elapsed, 39/54 actions completed.
[WARNING] injectable_generator:injectable_config_builder on lib/core/app/app_injector.dart:
Missing dependencies in wled/core/app/app_injector.dart

[DeviceControlBloc] depends on unregistered type [AppRouter] from package:wled/core/core.dart
[DeviceListBloc] depends on unregistered type [AppRouter] from package:wled/core/core.dart

Did you forget to annotate the above class(s) or their implementation with @injectable?
or add the right environment keys?
------------------------------------------------------------------------

[INFO] Running build completed, took 26.1s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 82ms

[INFO] Succeeded after 26.2s with 12 outputs (62 actions)
```
</details>

**Comment by bibekmakaju** [comment] 2021-09-29 11:07
> > the only way I found to workarround it some-how, but it looks quite ugly with adapter name string, hope Hive will be improved to fix it:
> > ```dart
> > import 'package:freezed_annotation/freezed_annotation.dart';
> > import 'package:hive/hive.dart';
> > 
> > part 'immutable_class.freezed.dart';
> > part 'immutable_class.g.dart';
> > 
> > @freezed
> > abstract class ImmutableClass with _$ImmutableClass {
> >   @HiveType(typeId: 5, adapterName: 'ImmutableClassAdapter')
> >   const factory ImmutableClass({
> >     @JsonKey(name: 'id', required: true, disallowNullValue: true) @HiveField(0) int id,
> >     @HiveField(1) int someField1,
> >     @HiveField(2) String someField2,
> >   }) = _ImmutableClass;
> > 
> >   factory ImmutableClass.fromJson(Map<String, dynamic> json) => _$ImmutableClassFromJson(json);
> > }
> > ```
> 
> @themisir I have been using this solution since last 3-4 months. And I didn't get any issues. The problem with using Hive with Freezed is, Freezed creates Private classes (_$*), so for example, our class `Product` will have adapter called `_$ProductAdapter`, which we won't be able to access anywhere.
> 
> The solution is to manually provide `adapterName` just as this solution and it would work PERFECTLY.
> 
> So, to conclude, neither of the libraries are at fault.

how to register this adapter?

**Comment by dJani97** [comment] 2022-10-22 13:02
Hey, I have a project that's more than a year old. This used to work back then:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'favorite.freezed.dart';
part 'favorite.g.dart';

@freezed
class Favorite with _$Favorite {
  @HiveType(typeId: 0, adapterName: 'FavoriteAdapter')
  const factory Favorite(
    @HiveField(0) String uuid,
    @HiveField(1) String name,
    @HiveField(2) ObjectType type,
  ) = _Favorite;

  factory Favorite.fromJson(Map<String, dynamic> json) => _$FavoriteFromJson(json);
}

@HiveType(typeId: 1, adapterName: 'ObjectTypeAdapter')
enum ObjectType {
  @HiveField(0)
  topic,
  @HiveField(1)
  post,
}
```

But now when I run the generator, the `FavoriteAdapter` class in `favorite.g.dart` gets un-generated. I have to manually restore that piece of code after each run.

Related dependencies:
```yaml
hive_generator: ^1.1.3
freezed: ^2.2.0
json_serializable: ^6.5.3
```

**Comment by Shiba-Kar** [comment] 2023-04-14 16:27
@bibekmakaju

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  Hive.registerAdapter<Employee>(EmployeeType());
  Hive.registerAdapter<Role>(RoleType());
  await Hive.openBox<List<Employee>>('employees_box');
  runApp(const ProviderScope(child: MyApp()));
}
```

**Comment by rootux** [comment] 2023-10-03 04:36
Can't find my adapter and therefore can't register it
Tried to use 
Hive.registerAdapter<Profile>(ProfileAdapter()); - but I don't have access to Profiles adatper.

Here is some of the code
```dart
part 'profile.freezed.dart';
part 'profile.g.dart';

@freezed
class Profile with _$Profile{
  @HiveType(typeId: 5, adapterName: "ProfileAdapter")
  const factory Profile({
    @HiveField(1)
    required String name,
    @HiveField(2)
    required List<String> ideas,
    @HiveField(3)
    @Default(false) bool isAllowSomething
  }) = _Profile;
```
The generated profile.g.dart file does have
```dart
class ProfileAdapter extends TypeAdapter<_$ProfileImpl> {
```

But I can't seem to be able to access it to register it as an adapter

**Comment by rootux** [comment] 2023-10-03 04:50
**UPDATE**
❌  Small progress - it writes to hive - but when decoding (reading) from hive - 
On the latest `freezed` version I get
"type '_$ProfileImpl' is not a subtype of type 'Map<String, dynamic>' in type cast"

And for an older `freezed` of 2.3.5 I get
type '_$_Profile' is not a subtype of type 'Map<String, dynamic>' in type cast


For some reason the code snippets above didn't work for me - than I've set the `@HiveType` on the class and not on the factory like so :
```dart

part 'profile.freezed.dart';
part 'profile.g.dart';

@freezed
@HiveType(typeId: 5, adapterName: "ProfileAdapter")
class Profile with _$Profile{
  const factory Profile({
    @HiveField(1)
    required String name,
    @HiveField(2)
    required List<String> ideas,
    @HiveField(3)
    @Default(false) bool isAllowSomething
  }) = _Profile;

```

This is what being created
```dart
class ProfileAdapter extends TypeAdapter<Profile> {
```
which can be used when registering the adapter.

the issue is probably around those lines:
```dart
class ProfileAdapter extends TypeAdapter<_$_Profile> {
  @override
  final int typeId = 5;

  @override
  _$_Profile read(BinaryReader reader) {
```
the read method returns a `_$_Profile` where it might needs to read back a `Profile`
And does write but doesn't read back (See error in top message)
