### ISSUE TITLE
Why does hive_generator depend on a hosted version of hive?

### ISSUE THREAD

**Issue by Reprevise** [hivedb/hive#384] opened 2020-07-23 23:39 UTC
I'm trying to have all of my hive-related dependencies gotten from the repository itself, but hive_generator depends on a hosted version of hive rather than the one in the repository. Is there any particular reason for this or can it be changed?

**Comment by TheMisir** [comment] 2020-07-24 12:17
Duplicate of https://github.com/hivedb/hive/issues/385

**Closed by TheMisir** 2020-07-24 12:17 UTC
Labels: question
