### ISSUE TITLE
Hive error when opening boxes

### ISSUE THREAD

**Issue by JamesMutahi** [hivedb/hive#677] opened 2021-05-26 13:48 UTC
Got this error in production reported by sentry 

**Steps to Reproduce**
HiveError: HiveError: This should not happen. Please open an issue on GitHub.
  File "binary_reader_impl.dart", line 249, in BinaryReaderImpl.readFrame
  File "frame_helper.dart", line 17, in FrameHelper.framesFromBytes
  File "frame_io_helper.dart", line 41, in FrameIoHelper.framesFromFile
  File "<asynchronous suspension>"
  File "storage_backend_vm.dart", line 82, in StorageBackendVm.initialize
  File "<asynchronous suspension>"
  File "hive_impl.dart", line 106, in HiveImpl._openBox
  File "<asynchronous suspension>"
  File "hive_impl.dart", line 135, in HiveImpl.openBox
  File "<asynchronous suspension>"
  File "auth_provider.dart", line 34, in AuthProvider.openHive
  File "<asynchronous suspension>"
  File "auth_repository.dart", line 34, in AuthRepository.openHive
  File "<asynchronous suspension>"
  File "auth_bloc.dart", line 16, in AuthBloc.mapEventToState
  File "<asynchronous suspension>"

**Code sample**
```
  Future<void> openHive() async {
    await Hive.openBox<User>("UserBox");
}
```

**Version**
 - Platform: Android
 - Flutter version: 1.22.6
 - hive: ^1.4.4+1
 - hive_flutter: ^0.3.1

**Comment by TheMisir** [comment] 2021-05-26 14:09
Duplicate of #263

**Closed by TheMisir** 2021-05-26 14:09 UTC
Labels: problem
