### ISSUE TITLE
flutter hive: Unhandled Exception: RangeError: Not enough bytes available

### ISSUE THREAD

**Issue by tazik561** [hivedb/hive#498] opened 2020-11-24 09:00 UTC
In my flutter application I have used hive to persist my data.Before i use my custom adapter like this:
 

    class MessageModelAdapter
        extends TypeAdapter<GetPushNotificationContentListResponse> {
      @override
      final typeId = 4;
    
      @override
      GetPushNotificationContentListResponse read(BinaryReader reader) {
        var numOfFields = reader.readByte();
        var fields = <int, dynamic>{
          for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
        };
        return GetPushNotificationContentListResponse(
          message: fields[0],
          messageId: fields[1],
          notificationType: fields[2],
          pushId: fields[3],
          sendDate: fields[4],
        );
      }
    
      @override
      void write(BinaryWriter writer, GetPushNotificationContentListResponse obj) {
        writer
          ..writeByte(5)
          ..writeByte(0)
          ..write(obj.message)
          ..writeByte(1)
          ..write(obj.messageId)
          ..writeByte(2)
          ..write(obj.notificationType)
          ..writeByte(3)
          ..write(obj.pushId)
          ..writeByte(4)
          ..write(obj.sendDate);
      }
    }

But now i am trying to use like this:

    class MessageModelAdapter
        extends TypeAdapter<GetPushNotificationContentListResponse> {
      @override
      final typeId = 4;
    
      @override
      GetPushNotificationContentListResponse read(BinaryReader reader) {
    
        return GetPushNotificationContentListResponse()
          ..message = reader.read()
          ..messageId = reader.read()
          ..notificationType = reader.read()
          ..pushId = reader.read()
          ..sendDate = reader.read();
      }
    
      @override
      void write(BinaryWriter writer, GetPushNotificationContentListResponse obj) {
        writer
          ..write(obj.message)
          ..write(obj.messageId)
          ..write(obj.notificationType)
          ..write(obj.pushId)
          ..write(obj.sendDate);
      }
    }

But when i run application i got this error:

    E/flutter ( 6361): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError: Not enough bytes available.
    E/flutter ( 6361): #0      BinaryReaderImpl._requireBytes
    package:hive/…/binary/binary_reader_impl.dart:49
    E/flutter ( 6361): #1      BinaryReaderImpl.readByteList
    package:hive/…/binary/binary_reader_impl.dart:142
    E/flutter ( 6361): #2      BinaryReaderImpl.read
    package:hive/…/binary/binary_reader_impl.dart:304
    E/flutter ( 6361): #3      MessageModelAdapter.read
    package:iparsian_flutter/…/database/push_message_box.dart:150
    E/flutter ( 6361): #4      BinaryReaderImpl.read
    package:hive/…/binary/binary_reader_impl.dart:325
    E/flutter ( 6361): #5      BinaryReaderImpl.readFrame
    package:hive/…/binary/binary_reader_impl.dart:273
    E/flutter ( 6361): #6      FrameHelper.framesFromBytes
    package:hive/…/binary/frame_helper.dart:17
    E/flutter ( 6361): #7      FrameIoHelper.framesFromFile
    package:hive/…/io/frame_io_helper.dart:41
    E/flutter ( 6361): <asynchronous suspension>
    E/flutter ( 6361): #8      StorageBackendVm.initialize
    package:hive/…/vm/storage_backend_vm.dart:82
    E/flutter ( 6361): <asynchronous suspension>
    E/flutter ( 6361): #9      BoxBaseImpl.initialize
    package:hive/…/box/box_base_impl.dart:90
    E/flutter ( 6361): #10     HiveImpl._openBox
    package:hive/src/hive_impl.dart:106

How can i change implementation of adapter without problem?

**Comment by TheMisir** [comment] 2020-11-24 11:41
Duplicate of #424

**Closed by TheMisir** 2020-11-24 11:41 UTC
Labels: question

**Comment by tazik561** [comment] 2020-11-24 12:26
I don't want to reinstall the application. I can not force the user to reinstall application .user has a data and they don't want to deleted.
There is no way to changing model structure without reinstall app?

**Comment by musman-deve** [comment] 2022-12-28 13:05
If you have made any changes in Adapter then try re-generating it. It'll fix your issue.
