### ISSUE TITLE
how to generate adaptor for nested classes?

### ISSUE THREAD

**Issue by chcarmen** [hivedb/hive#481] opened 2020-10-31 08:48 UTC
**Question**
how to generate type adaptor for nested classes ? especiallly those inhertied from other class.

like the following code, I need to store User data to Hive Box, so how to generate related adaptors?

**Code sample**
```dart
class User extends BaseUser {
    User();

    bool isVerified;
    Avatar avatar;
}

class Avatar {
    Avatar();
   
   String cdn;
   String url;
}

class BaseUser extends Base {
    BaseUser();
   
    int age;
    String name;
}

class Base {
    Base();

    String id;
    String createdAt；
}

```

**Version**
 - Platform:  Android
 - Flutter version:  V1.22.2
 - Hive version:  V1.4.4+1

**Comment by chcarmen** [comment] 2020-10-31 09:41
I looked through some of the related issues here, seems it still has lots of problems about interitance class adaptor generation. also it needs tons of code modification. 

so i am wondering that is storing only plan json data much easier than storing class? in this case, i can reuse the current toJson() and fromJson() functions which generated by json_serializable package to store class data, without modifying current data model, that is, no need to add tons of @HiveField(x) to all related classes (child class, parent class, member class, enums....).
only thing we have to pay attention is, correctly serializabling and deserializabling  json data.

any comments?

**Comment by TheMisir** [comment] 2020-10-31 14:07
I'm planning to implement inheritance soon. I need to do a bit research about dart analyzer.

**Comment by TheMisir** [comment] 2020-10-31 14:07
Duplicate of #442

**Closed by TheMisir** 2020-10-31 14:07 UTC
Labels: question
