### ISSUE TITLE
TypeRegistryImpl.findAdapterForValue() return incorrect adapter

### ISSUE THREAD

**Issue by rockerhieu** [hivedb/hive#499] opened 2020-11-25 04:18 UTC
**Steps to Reproduce**
- There are 4 data classes: A, B, C, D whose type id from 0 to 3.
- Generate adapters with `hive_generator`
- Register all adapters in unit test
- Write an object of D
- Read the object back
- Error: `type '_$_D' is not a subtype of type '_$_A' of 'obj'`. This is because AAdapter is used for parsing a D object

**Code sample**
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'main.freezed.dart';

part 'main.g.dart';

@freezed
abstract class A with _$A {
  @HiveType(typeId: 0)
  const factory A({
    @HiveField(0) String foo,
    @HiveField(1) String bar,
  }) = _A;
}

@freezed
abstract class B with _$B {
  @HiveType(typeId: 1)
  const factory B({
    @HiveField(2) String foo,
    @HiveField(3) String bar,
  }) = _B;
}

@freezed
abstract class C with _$C {
  @HiveType(typeId: 2)
  const factory C({
    @HiveField(4) String foo,
    @HiveField(5) String bar,
  }) = _C;
}

@freezed
abstract class D with _$D {
  @HiveType(typeId: 3)
  const factory D({
    @HiveField(6) String foo,
    @HiveField(7) String bar,
  }) = _D;
}
```

```dart
import 'dart:io';

import 'package:formula/main.dart';
import 'package:hive/hive.dart';
import 'package:test/test.dart';

void main() {
  group('LocalConfig', () {
    Box box;

    setUp(() async {
      final temp = await Directory.systemTemp.createTemp();
      <TypeAdapter>[
        AAdapter(),
        BAdapter(),
        CAdapter(),
        DAdapter(),
      ]
          .where((adapter) => !Hive.isAdapterRegistered(adapter.typeId))
          .forEach((adapter) => Hive.registerAdapter(adapter));
      print(temp.path);
      Hive.init(temp.path);
      box = await Hive.openBox('test');
    });

    tearDown(() async {
      await box.deleteFromDisk();
    });

    test('read/write', () async {
      expect(box.get('key'), isNull);
      box.put('key', D(foo: 'foo', bar: 'bar'));
      expect(box.get('key').foo, 'foo');
      expect(box.get('key').bar, 'bar');
    });
  });
}
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.4
 - Hive version: hive 1.4.4 and hive_generator 0.8.2

```yaml
dependencies:
  flutter:
    sdk: flutter

  hive: ^1.4.4
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

  freezed: ^0.12.3
  build_runner: any
  hive_generator: ^0.8.2
```

**Comment by rockerhieu** [comment] 2020-12-01 20:13
@leisim: hope you enjoyed the holidays.

Do you have a chance to take a look at this issue?

**Comment by TheMisir** [comment] 2020-12-01 20:53
@rockerhieu hive doesn't officially supports value builders. I'm not planning to supporting value builder (working on issues related to value builders) in near future.

**Comment by rockerhieu** [comment] 2020-12-02 23:02
@TheMisir I don't think this have anything to do with value builder (or freezed in this case). The issue occur without `freezed` too: `type 'D' is not a subtype of type 'A' of 'obj'`

```dart
import 'package:hive/hive.dart';

part 'main.g.dart';

@HiveType(typeId: 0)
class A {
  @HiveField(0)
  String foo;
  @HiveField(1)
  String bar;

  A({this.foo, this.bar});
}

@HiveType(typeId: 1)
class B {
  @HiveField(2)
  String foo;
  @HiveField(3)
  String bar;

  B({this.foo, this.bar});
}

@HiveType(typeId: 2)
class C {
  @HiveField(4)
  String foo;
  @HiveField(5)
  String bar;

  C({this.foo, this.bar});
}

@HiveType(typeId: 3)
class D {
  @HiveField(6)
  String foo;
  @HiveField(7)
  String bar;

  D({this.foo, this.bar});
}
```

**Comment by TheMisir** [comment] 2020-12-03 06:48
Maybe you've changed typeId-s of the adapters?

**Comment by rockerhieu** [comment] 2020-12-03 16:35
This is the code I used for registering the adapters:

```dart
<TypeAdapter>[
        AAdapter(),
        BAdapter(),
        CAdapter(),
        DAdapter(),
      ]
          .where((adapter) => !Hive.isAdapterRegistered(adapter.typeId))
          .forEach((adapter) => Hive.registerAdapter(adapter));
```

I didn't change the typeId of any of the adapters.

**Comment by rockerhieu** [comment] 2020-12-08 20:31
@TheMisir is there anything else that I should provide for reproducing the issue?

**Comment by softronaut** [comment] 2021-01-03 17:51
I have same issue.
```dart
@HiveType(typeId: 0)
class Contact extends Equatable {
  @HiveField(0)
  final String username;
  @HiveField(1)
  final Color color;

  Contact({@required String username, Color color}) // For MaterialColor class handling
      : this.username = "@$username",
        this.color = Color(color.value);

  @override
  List<Object> get props => [username];
}

class ColorAdapter extends TypeAdapter<Color> {
  @override
  Color read(BinaryReader reader) {
    final colorValue = reader.readInt();
    return Color(colorValue);
  }

  @override
  void write(BinaryWriter writer, Color obj) {
    writer.writeInt(obj.value);
  }

  @override
  int get typeId => 223;
}
```

The error is:
> type 'Contact' is not a subtype of type 'Color' of 'obj'

**Comment by TheMisir** [comment] 2021-01-03 19:17
> I have same issue.
> 
> ```dart
> @HiveType(typeId: 0)
> class Contact extends Equatable {
>   @HiveField(0)
>   final String username;
>   @HiveField(1)
>   final Color color;
> 
>   Contact({@required String username, Color color}) // For MaterialColor class handling
>       : this.username = "@$username",
>         this.color = Color(color.value);
> 
>   @override
>   List<Object> get props => [username];
> }
> 
> class ColorAdapter extends TypeAdapter<Color> {
>   @override
>   Color read(BinaryReader reader) {
>     final colorValue = reader.readInt();
>     return Color(colorValue);
>   }
> 
>   @override
>   void write(BinaryWriter writer, Color obj) {
>     writer.writeInt(obj.value);
>   }
> 
>   @override
>   int get typeId => 223;
> }
> ```
> 
> The error is:
> 
> > type 'Contact' is not a subtype of type 'Color' of 'obj'
> 
> I'll try to reproduce this from scratch again, may be I missed a minor point.

ColorAdapter and Contact class? Am I missing something here?

**Comment by softronaut** [comment] 2021-01-03 20:18
I'm generating `ContactAdapter` with `Contact` class and using `ColorAdapter` to register `Color` class. Then using `Color` inside `Contact` but it gives that error.

**Comment by softronaut** [comment] 2021-01-10 20:18
This issue makes the library unusable. I don't know what's causing this, I have used Hive before couple of times but never faced this. I'm planning move whole structure to `sqflite` 🙁

**Comment by rockerhieu** [comment] 2021-01-10 21:27
@TheMisir 

This is all you need to reproduce the error:

```dart
import 'package:hive/hive.dart';

part 'main.g.dart';

@HiveType(typeId: 0)
class A {
  @HiveField(0)
  String foo;
  @HiveField(1)
  String bar;

  A({this.foo, this.bar});
}

@HiveType(typeId: 1)
class B {
  @HiveField(2)
  String foo;
  @HiveField(3)
  String bar;

  B({this.foo, this.bar});
}

@HiveType(typeId: 2)
class C {
  @HiveField(4)
  String foo;
  @HiveField(5)
  String bar;

  C({this.foo, this.bar});
}

@HiveType(typeId: 3)
class D {
  @HiveField(6)
  String foo;
  @HiveField(7)
  String bar;

  D({this.foo, this.bar});
}
```

```dart
import 'dart:io';

import 'package:formula/main.dart';
import 'package:hive/hive.dart';
import 'package:test/test.dart';

void main() {
  group('LocalConfig', () {
    Box box;

    setUp(() async {
      final temp = await Directory.systemTemp.createTemp();
      <TypeAdapter>[
        AAdapter(),
        BAdapter(),
        CAdapter(),
        DAdapter(),
      ]
          .where((adapter) => !Hive.isAdapterRegistered(adapter.typeId))
          .forEach((adapter) => Hive.registerAdapter(adapter));
      print(temp.path);
      Hive.init(temp.path);
      box = await Hive.openBox('test');
    });

    tearDown(() async {
      await box.deleteFromDisk();
    });

    test('read/write', () async {
      expect(box.get('key'), isNull);
      box.put('key', D(foo: 'foo', bar: 'bar'));
      expect(box.get('key').foo, 'foo');
      expect(box.get('key').bar, 'bar');
    });
  });
}
```

**Comment by TheMisir** [comment] 2021-01-10 21:29
> This issue makes the library unusable. I don't know what's causing this, I have used Hive before couple of times but never faced this. I'm planning move whole structure to `sqflite` 🙁
> Btw, it's not related with `TypeAdapter`s relations. It's just happens randomly.
> I was using `json_serializable`, removed it and tried from scratch, nothing changed.

The issue is caused by some sort of invalid configuration or something else I don't know. But in OP's code it's possible that hive uses wrong adapter for writing data because classes inherited from each other. Maybe that's the case of the issue. I'll do a bit research if it's possible to prioritize exact types before implementations (I mean if Bear extends Animal class, and you try to put instance of Bear inside hive, hive might use AnimalAdapter for serializing data because Bear is also an Animal). Because hive uses [a simple logic](https://github.com/hivedb/hive/blob/master/hive/lib/src/registry/type_registry_impl.dart#L11) to find matching adapter to serialize data.

**Comment by TheMisir** [comment] 2021-01-10 21:29
Thanks @rockerhieu  I'm checking

**Comment by TheMisir** [comment] 2021-01-10 22:23
When you replace <TypeAdapter>[ ... ].forEach part with individual registerAdapter calls It works as expected.

![image](https://user-images.githubusercontent.com/29130291/104136332-d9e4d680-53ae-11eb-9b03-9467d5694536.png)

It works even if you just remove <TypeAdapter> before [. I just discovered this weird behavior in dart:

![image](https://user-images.githubusercontent.com/29130291/104137040-61ccdf80-53b3-11eb-9dbc-7529c3417071.png)

Because dart thinks entries of generic type list is generic type of `dynamic` (which translates into `registerAdapter<dynamic>(...)` in our issue) and everything is `dynamic` in dart, hive uses first registered adapter to (de)serialize all classes.

I hope I could explain the issue. To solve it you can remove `<TypeAdapter>` part or call `registerAdapter` separately for each adapter.

**Comment by softronaut** [comment] 2021-01-10 22:37
Wow, I was registering `Adapter` exact same way with @rockerhieu , not I'm giving it a try!

**Comment by TheMisir** [comment] 2021-01-10 22:38
I'm closing this since the issue is caused by dart itself, rather than hive. @ me if you encounter any other errors 😄

**Closed by TheMisir** 2021-01-10 22:38 UTC
Labels: problem

**Comment by TheMisir** [comment] 2021-01-10 22:40
btw sorry for late answering, I'm very busy for last a few months 😞
