### ISSUE TITLE
Error: Getter not found: 'ENUM'. 

### ISSUE THREAD

**Issue by chinloyal** [hivedb/hive#396] opened 2020-08-02 13:41 UTC
**Steps to Reproduce**
Running
```
flutter packages pub run build_runner build
```
Causes
>[SEVERE] /opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive_generator-0.7.1/lib/src/type_adapter_generator.dart:60:76: Error: Getter not found: 'ENUM'.    check(element.kind == ElementKind.CLASS || element.kind == ElementKind.ENUM,    
                                                                      
**Code Sample**
```dart
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'qpin.g.dart';

@HiveType(typeId: 0) @JsonSerializable()
class MyClass extends HiveObject{
  @HiveField(0)
  int field;

  MyClass(this.field);

  factory MyClass.fromJson(Map<String, dynamic> json) => _$MyClassFromJson(json);

  Map<String, dynamic> toJson() => _$MyClassToJson(this);
}

```

**Version**
 - Platform: Linux
 - Flutter version: 1.17.5
 - Hive version: ^1.4.2
- Hive Generator: ^0.7.1

**Comment by TheMisir** [comment] 2020-08-02 13:52
Duplicate of #390

**Closed** 2020-08-02 13:52 UTC
Labels: problem
