### ISSUE TITLE
HiveError (HiveError: This should not happen. Please open an issue on GitHub.)

### ISSUE THREAD

**Issue by UlanNurmatov** [hivedb/hive#497] opened 2020-11-23 19:27 UTC
**Steps to Reproduce**
I'm using library **receive_sharing_intent: ^1.4.1** to share images from internet into my app. 
Everything worked fine, but today after sharing image from Chrome I got this error. 
I restarted the app, but it crashed.

> E/flutter (24049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
> [38;5;248mE/flutter (24049): #0      BinaryReaderImpl.readFrame[39;49m
> [38;5;248mE/flutter (24049): #1      FrameHelper.framesFromBytes[39;49m
> [38;5;248mE/flutter (24049): #2      FrameIoHelper.framesFromFile[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #3      StorageBackendVm.initialize[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #4      BoxBaseImpl.initialize[39;49m
> [38;5;248mE/flutter (24049): #5      HiveImpl._openBox[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #6      HiveImpl.openBox[39;49m
> [38;5;248mE/flutter (24049): #7      main[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;244mE/flutter (24049): #8      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:231:25)[39;49m
> [38;5;244mE/flutter (24049): #9      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
> [38;5;244mE/flutter (24049): #10     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
> [38;5;244mE/flutter (24049): #11     _runZoned  (dart:async/zone.dart:1630:10)[39;49m
> [38;5;244mE/flutter (24049): #12     runZonedGuarded  (dart:async/zone.dart:1618:12)[39;49m
> [38;5;244mE/flutter (24049): #13     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:223:5)[39;49m
> [38;5;244mE/flutter (24049): #14     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)[39;49m
> [38;5;244mE/flutter (24049): #15     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m
> E/flutter (24049):
> E/flutter (24049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
> [38;5;248mE/flutter (24049): #0      BinaryReaderImpl.readFrame[39;49m
> [38;5;248mE/flutter (24049): #1      FrameHelper.framesFromBytes[39;49m
> [38;5;248mE/flutter (24049): #2      FrameIoHelper.framesFromFile[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #3      StorageBackendVm.initialize[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #4      BoxBaseImpl.initialize[39;49m
> [38;5;248mE/flutter (24049): #5      HiveImpl._openBox[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;248mE/flutter (24049): #6      HiveImpl.openBox[39;49m
> [38;5;248mE/flutter (24049): #7      main[39;49m
> E/flutter (24049): <asynchronous suspension>
> [38;5;244mE/flutter (24049): #8      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:231:25)[39;49m
> [38;5;244mE/flutter (24049): #9      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
> [38;5;244mE/flutter (24049): #10     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
> [38;5;244mE/flutter (24049): #11     _runZoned  (dart:async/zone.dart:1630:10)[39;49m
> [38;5;244mE/flutter (24049): #12     runZonedGuarded  (dart:async/zone.dart:1618:12)[39;49m
> [38;5;244mE/flutter (24049): #13     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:223:5)[39;49m
> [38;5;244mE/flutter (24049): #14     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)[39;49m
> [38;5;244mE/flutter (24049): #15     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m
> E/flutter (24049):

**Version**
 - Platform: Android
 - Flutter version: Flutter (Channel master, 1.24.0-2.0.pre.40)
 - Hive version:
  hive: ^1.4.4
  hive_flutter: ^0.3.1

**Comment by stanleyillidge** [comment] 2020-11-29 18:12
tengo un problema similar, que se debe hacer ante este problema?

**Comment by TheMisir** [comment] 2020-11-30 11:09
Duplicate of #263

**Closed by TheMisir** 2020-11-30 11:09 UTC
Labels: problem
