### ISSUE TITLE
Can't open box anymore

### ISSUE THREAD

**Issue by vixez** [hivedb/hive#472] opened 2020-10-19 15:09 UTC
**Steps to Reproduce**
I don't know how this happened, it just did this after hot reloading my app.

**Error**
```
E/flutter (20992): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
E/flutter (20992): #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
E/flutter (20992): #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
E/flutter (20992): #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
E/flutter (20992): <asynchronous suspension>
E/flutter (20992): #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:30)
E/flutter (20992): <asynchronous suspension>
E/flutter (20992): #4      BoxBaseImpl.initialize (package:hive/src/box/box_base_impl.dart:90:20)
E/flutter (20992): #5      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:22)
E/flutter (20992): <asynchronous suspension>
E/flutter (20992): #6      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
E/flutter (20992): #7      Base._openBox (package:gd_translations_settings/src/base/base.dart:101:23)
E/flutter (20992): #8      Base.openFallbackBox (package:gd_translations_settings/src/base/base.dart:128:32)
E/flutter (20992): #9      Translations._checkFirstRun (package:gd_translations_settings/src/translations/translations.dart:93:13)
E/flutter (20992): #10     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20992): #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20992): #12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20992): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20992): #14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20992): #15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20992): #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20992): #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20992): #18     Base.boxExists (package:gd_translations_settings/src/base/base.dart)
E/flutter (20992): #19     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20992): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20992): #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20992): #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20992): #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20992): #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20992): #25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20992): #26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20992): #27     HiveImpl.boxExists (package:hive/src/hive_impl.dart)
E/flutter (20992): #28     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20992): #29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20992): #30     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20992): #31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20992): #32     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20992): #33     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20992): #34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20992): #35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20992): #36     BackendManager.boxExists (package:hive/src/backend/vm/backend_manager.dart)
E/flutter (20992): #37     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20992): #38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20992): #39     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20992): #40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20992): #41     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20992): #42     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20992): #43     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (20992): #44     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20992): #45     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20992): #46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20992): #47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20992): #48     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (20992): #49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (20992): 
```

**Version**
 - Platform: Android
 - Flutter version: 1.23.0-18.1.pre
 - Hive version: ^1.4.4+1
 - Hive Flutter version: ^0.3.1

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at
      /Users/glennruysschaert/development/flutter
    • Framework revision 198df796aa (4 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.80

• No issues found!
```

**Comment by TheMisir** [comment] 2020-10-19 21:22
Unfortunately we don't have reproducible example to take a look at what causes the issue.

Duplicate of #263

**Comment by TheMisir** [comment] 2020-10-19 21:22
Duplicate of #263

**Closed by TheMisir** 2020-10-19 21:22 UTC
Labels: problem

**Comment by vixez** [comment] 2020-10-20 10:09
I think it this is caused by either
- Not awaiting a box closing before opening a new one
- Opening the same box in rapid succession
