### ISSUE TITLE
Mobile App building  in debug mode but not in profile mode

### ISSUE THREAD

**Issue by skylum1** [hivedb/hive#701] opened 2021-06-21 21:23 UTC
**Steps to Reproduce**

Created a small repo showcasing the issue ,please clone it and let me know if you are also getting same error .
https://github.com/skylum1/Hive-Problem-Demo.git

**Version**
 - Platform: Android
 - Flutter version: Flutter 2.0.1 • channel stable •
 - Hive version: 2.0.4

**Comment by mbaumgartenbr** [comment] 2021-06-21 21:31
Hey!

I'm not sure if this is the problem, but you're importing `path_provider` as a dev dependency, those don't get included in the apk bundle.

Try moving it to regular dependencies or get rid of it entirely by using Hive.initFlutter (already handles the path_provider part for you).

**Comment by skylum1** [comment] 2021-06-21 21:49
No , this is not the problem I changed it but it still gives same error.

**Comment by TheMisir** [comment] 2021-06-21 22:16
I could reproduce it.

<details>
<summary>**Build logs**</summary>

```
$ flutter build apk --profile

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

../../third_party/dart/runtime/vm/compiler/backend/il.h: 1028: error: unreachable code
version=2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_simarm64"
pid=63260, thread=259, isolate_group=isolate(0x7feef4017a00), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=0                               
  pc 0x000000010ba5848b fp 0x00007ffee47d22c0 Dart_DumpNativeStackTrace+0x4b
  pc 0x000000010b43afe2 fp 0x00007ffee47d23a0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x000000010b69282c fp 0x00007ffee47d23c0 dart::Instruction::DeoptimizationTarget() const+0x2c
  pc 0x000000010b863aac fp 0x00007ffee47d2430 dart::FlowGraph::InsertConversion(dart::Representation, dart::Representation, dart::Value*, bool)+0x9cc
  pc 0x000000010b864a57 fp 0x00007ffee47d24a0 dart::FlowGraph::SelectRepresentations()+0x997
  pc 0x000000010b979572 fp 0x00007ffee47d24c0 dart::CompilerPass_SelectRepresentations::DoBody(dart::CompilerPassState*) const+0x22
  pc 0x000000010b97a5fc fp 0x00007ffee47d2540 dart::CompilerPass::Run(dart::CompilerPassState*) const+0xbc
  pc 0x000000010b97ace2 fp 0x00007ffee47d2570 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)+0x2c2
  pc 0x000000010b82f9ba fp 0x00007ffee47d2c30 dart::PrecompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x73a
  pc 0x000000010b82efb6 fp 0x00007ffee47d2dd0 dart::PrecompileFunctionHelper(dart::Precompiler*, dart::CompilationPipeline*, dart::Function const&, bool)+0x636
  pc 0x000000010b82b7a9 fp 0x00007ffee47d2ea0 dart::Precompiler::CompileFunction(dart::Precompiler*, dart::Thread*, dart::Zone*, dart::Function const&)+0x1b9
  pc 0x000000010b7fbc84 fp 0x00007ffee47d3210 dart::Precompiler::DoCompileAll()+0x38c4
  pc 0x000000010b7f81ec fp 0x00007ffee47d3750 dart::Precompiler::CompileAll()+0x24bc
  pc 0x000000010ba53d96 fp 0x00007ffee47d38a0 Dart_Precompile+0x2d6     
  pc 0x000000010b433118 fp 0x00007ffee47d3e40 dart::bin::main(int, char**)+0x13e8
  pc 0x00007fff20431f5d fp 0x00007ffee47d3e58 start+0x1                 
-- End of DumpStackTrace                                                
Dart snapshot generator failed with exit code -6                        
../../third_party/dart/runtime/vm/compiler/backend/il.h: 1028: error: unreachable code
version=2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64" 
pid=63261, thread=259, isolate_group=isolate(0x7f974580be00), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=0                               
  pc 0x000000010637330b fp 0x00007ffee9eb82d0 Dart_DumpNativeStackTrace+0x4b
  pc 0x0000000105d51cd2 fp 0x00007ffee9eb83b0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000000105faacec fp 0x00007ffee9eb83d0 dart::Instruction::DeoptimizationTarget() const+0x2c
  pc 0x00000001061762fc fp 0x00007ffee9eb8440 dart::FlowGraph::InsertConversion(dart::Representation, dart::Representation, dart::Value*, bool)+0x9cc
  pc 0x00000001061772a7 fp 0x00007ffee9eb84b0 dart::FlowGraph::SelectRepresentations()+0x997
  pc 0x0000000106294af2 fp 0x00007ffee9eb84d0 dart::CompilerPass_SelectRepresentations::DoBody(dart::CompilerPassState*) const+0x22
  pc 0x0000000106295b7c fp 0x00007ffee9eb8550 dart::CompilerPass::Run(dart::CompilerPassState*) const+0xbc
  pc 0x0000000106296262 fp 0x00007ffee9eb8580 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)+0x2c2
  pc 0x0000000106139afa fp 0x00007ffee9eb8c40 dart::PrecompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x73a
  pc 0x00000001061390f6 fp 0x00007ffee9eb8de0 dart::PrecompileFunctionHelper(dart::Precompiler*, dart::CompilationPipeline*, dart::Function const&, bool)+0x636
  pc 0x00000001061358e9 fp 0x00007ffee9eb8eb0 dart::Precompiler::CompileFunction(dart::Precompiler*, dart::Thread*, dart::Zone*, dart::Function const&)+0x1b9
  pc 0x0000000106105e84 fp 0x00007ffee9eb9220 dart::Precompiler::DoCompileAll()+0x38c4
  pc 0x00000001061023ec fp 0x00007ffee9eb9760 dart::Precompiler::CompileAll()+0x24bc
  pc 0x000000010636ec16 fp 0x00007ffee9eb98b0 Dart_Precompile+0x2d6     
  pc 0x0000000105d49e08 fp 0x00007ffee9eb9e50 dart::bin::main(int, char**)+0x13e8
  pc 0x00007fff20431f5d fp 0x00007ffee9eb9e60 start+0x1                 
-- End of DumpStackTrace                                                
Dart snapshot generator failed with exit code -6                        
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/misir/Workspace/tools/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildProfile'.            
> Process 'command '/Users/misir/Workspace/tools/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 23s                                                     
Running Gradle task 'assembleProfile'...                                
Running Gradle task 'assembleProfile'... Done                      24.6s
Gradle task assembleProfile failed with exit code 1
```
</details>

**Comment by TheMisir** [comment] 2021-06-21 22:29
It's so weird that removing `status.index` fixes the issue. Which is not related to hive btw. Probably caused by some internal dart issue.

**Comment by skylum1** [comment] 2021-06-22 08:51
@TheMisir  ,I thought since not registering type adapter also seemingly fixes the issue ,so maybe it is causing some weird interpretation of Hive annotated class

**Closed** 2021-07-05 10:40 UTC
Labels: problem
