### ISSUE TITLE
casting Box<Map<String , dynamic>> to List<Map<String , dynamic >> throws _CastError

### ISSUE THREAD

**Issue by amini-rezza** [hivedb/hive#489] opened 2020-11-13 16:49 UTC
**Steps to Reproduce**
1 _ Opening box with <Map<>String , dynamic> generic
2 _ adding some valid map to box using put method
3 _ reading box.values from box 

**Code sample**

void main() async {
  await Hive.initFlutter();
  await Hive.openBox<Map<String, dynamic>>('activities');
}

Activity activity = Activity(
    id: 'uniqueId',
    name: 'Doing HomeWork',              
 );

box = Hive.box<Map<String, dynamic>>('activities');
box.put(activity.id, activity.toJson()); // works fine

box = Hive.box<Map<String, dynamic>>('activities');
List<Map<String, dynamic>> list = box.values.toList(); // throws  "type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast" after the first Hot restart or closing and opening application

// stacktarce info doesnt say much , but here it is

When the exception was thrown, this was the stack
#0      Keystore.getValues.<anonymous closure>package:hive/…/box/keystore.dart:122
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#2      new List.from (dart:core-patch/array_patch.dart:50:19)
#3      new List.of (dart:core-patch/array_patch.dart:68:17)
#4      Iterable.toList (dart:core/iterable.dart:404:12)

`

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.3 • channel stable
 - Hive version: 1.4.4+1
 - hive_flutter: 0.3.1

**Comment by TheMisir** [comment] 2020-11-13 18:45
Duplicate of #295

**Closed by TheMisir** 2020-11-13 18:45 UTC
Labels: problem

**Comment by amini-rezza** [comment] 2020-11-13 18:50
it isnt duplicate of 295 issue,
it doesnt work even after using both of these suggested workarounds

ps: i dont want to use an adapter

Unfortunately this is a limitation of the dart language. You can use 
```dart
var box = await Hive.openBox<Map>('boxName');
var map = box.get("myMap").cast<String, dynamic>();
```

or you create an object which contains your box and generate a Hive adapter. The adapter will handle the casting.

_Originally posted by @leisim in https://github.com/hivedb/hive/issues/295#issuecomment-636486984_

**Comment by 2shrestha22** [comment] 2022-08-11 11:47
Do it like this. 
```dart
void main() async {
  await Hive.initFlutter();
  await Hive.openBox<Map<dynamic, dynamic>>('activities');
}

Activity activity = Activity(
    id: 'uniqueId',
    name: 'Doing HomeWork',              
 );

box = Hive.box<Map<dynamic, dynamic>>('activities');
box.put(activity.id, activity.toJson()); // works fine

box = Hive.box<Map<dynamic, dynamic>>('activities');
List<Map<String, dynamic>> list = box.values.map((e)=> e.cast<String, dynamic>()) .toList(); 
```
