### ISSUE TITLE
HiveError (HiveError: This should not happen. Please open an issue on GitHub.)

### ISSUE THREAD

**Issue by Tumist76** [hivedb/hive#428] opened 2020-09-10 11:05 UTC
**Steps to Reproduce**
I don't actually know how to reproduce the problem. I've just launched the debug version of the app and got the `HiveError (HiveError: This should not happen. Please open an issue on GitHub.)` exception. Well, here we are.

**Code sample**
```
Provide a few simple lines of code to show your problem.
```

**Call stack**

```
BinaryReaderImpl.readFrame (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/binary/binary_reader_impl.dart:249)
FrameHelper.framesFromBytes (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/binary/frame_helper.dart:17)
FrameIoHelper.framesFromFile (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/io/frame_io_helper.dart:41)
<asynchronous gap> (Unknown Source:0)
StorageBackendVm.initialize (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/backend/vm/storage_backend_vm.dart:82)
<asynchronous gap> (Unknown Source:0)
BoxBaseImpl.initialize (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/box/box_base_impl.dart:90)
HiveImpl._openBox (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/hive_impl.dart:90)
<asynchronous gap> (Unknown Source:0)
HiveImpl.openBox (/Users/tumist/Development/flutter/.pub-cache/git/hive-d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc/hive/lib/src/hive_impl.dart:111)
HiveService.getLastSavedVersion (/Users/tumist/Development/GitHub/mygeizer/lib/core/services/hive_service.dart:82)
AppVersionService._initService (/Users/tumist/Development/GitHub/mygeizer/lib/core/services/app_version_service.dart:66)
new AppVersionService (/Users/tumist/Development/GitHub/mygeizer/lib/core/services/app_version_service.dart:28)
independentServices.<anonymous closure> (/Users/tumist/Development/GitHub/mygeizer/lib/provider_setup.dart:23)
_CreateInheritedProviderState.value (/Users/tumist/Development/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/inherited_provider.dart:612)
_InheritedProviderScopeElement.value (/Users/tumist/Development/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/inherited_provider.dart:475)
Provider.of (/Users/tumist/Development/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/provider.dart:227)
_AppUpdateViewState.build.<anonymous closure> (/Users/tumist/Development/GitHub/mygeizer/lib/ui/widgets/home_page/home_page_update_view.dart:40)
_CreateInheritedProviderState.value (/Users/tumist/Development/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/inherited_provider.dart:612)
_InheritedProviderScopeElement.value (/Users/tumist/Development/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/inherited_provider.dart:475)
````
**Version**
 - Platform: iOS
 - Flutter version: 1.20.2
 - Hive version: 1.4.1+1

**Comment by leisim** [comment] 2020-09-25 19:23
Duplicate of #263 please provide sample code there if possible.

**Closed by leisim** 2020-09-25 19:23 UTC
Labels: problem
