### ISSUE TITLE
Getter not found: 'ENUM'

### ISSUE THREAD

**Issue by MahdiPishguy** [hivedb/hive#426] opened 2020-09-09 16:02 UTC
when i try to use `build_runner` in my application without implementing any class for `hive` i get this error

```
[SEVERE] /F:/software/flutter/.pub-cache/hosted/pub.dartlang.org/hive_generator-0.7.1/lib/src/type_adapter_generator.dart:60:76: Error: Getter not found: 'ENUM'.    check(element.kind == Eleme
ntKind.CLASS || element.kind == ElementKind.ENUM,     
```

**Comment by unacorbatanegra** [comment] 2020-09-14 15:51
Same trouble, any idea how to fix it?

**Comment by allobrox** [comment] 2020-09-16 05:56
try out #390

**Comment by unacorbatanegra** [comment] 2020-09-16 17:42
Thanks you so much!!!!

**Comment by TheMisir** [comment] 2020-09-17 09:13
Duplicate of #390

**Closed** 2020-09-17 09:13 UTC
Labels: problem
